### ISSUE TITLE
Scenario name

### ISSUE THREAD

**Issue by brbernardo90** [wswebcreation/multiple-cucumber-html-reporter#1]
Hi, I love this report but the scenarios name don't show.
Chrome Version 59.0.3071.115

In the example found in README.me, don't show too.

![report_issue](https://user-images.githubusercontent.com/15858324/28032943-aee018f0-6582-11e7-8066-682cadeee6e3.png)

**Comment by wswebcreation** [comment]
@brbernardo90 

Tnx for the compliment. 

Can you also post the following info here

- your version of cucumber
- your json

It looks like the scenario-name is not present in the json /  not set by Cucumber. I'm using this report also @DutchRailways and I don't have the problem

![image](https://user-images.githubusercontent.com/11979740/28033565-e6e7af34-65ae-11e7-8517-5a884c130d0b.png)

![image](https://user-images.githubusercontent.com/11979740/28033622-18364dde-65af-11e7-9a52-96c30a15ccf4.png)

**Comment by wswebcreation** [comment]
Can this issue be closed because in the issue [2](https://github.com/wswebcreation/multiple-cucumber-html-reporter/issues/2) and [3](https://github.com/wswebcreation/multiple-cucumber-html-reporter/issues/3) I see the scenario names

**Comment by brbernardo90** [comment]
@wswebcreation 

Great Work! Congratulations!

I thing that is the browser version cause the scenario names works fine with Safari. (The others issues was using it)

**Comment by wswebcreation** [comment]
ok, cool, will close the issue for now
