### ISSUE TITLE
'Feature chart' and 'Feature overview' are overlapping

### ISSUE THREAD

**Issue by daominhdam** [wswebcreation/multiple-cucumber-html-reporter#10]
Hi,
I used 'multiple cucumber report' latest version and config as below:
![image](https://user-images.githubusercontent.com/3110748/30372394-de57d08e-98a7-11e7-8a64-3e630ac7e778.png)
After I ran testcases successfully, so report html generated with chart and feature overview are overlapping (Chart is very big):
![image](https://user-images.githubusercontent.com/3110748/30372478-1d0c820c-98a8-11e7-94d1-e28f2f6f0d2d.png)

**Comment by wswebcreation** [comment]
Hi @daominhdam ,

That look like 2 big eyes looking at you ;-). This shouldn't happen. 

On which browser do you have this? And do you see the same when you look at this [report](https://wswebcreation.github.io/multiple-cucumber-html-reporter/)?

**Comment by daominhdam** [comment]
Hi @wswebcreation,
I resolved this issue now, because I used Windows OS and scale resolution my machine >100% (default).
So when I turn off it then view work well. 👍 
![image](https://user-images.githubusercontent.com/3110748/30372840-637ade36-98a9-11e7-8234-1188fcbccd72.png)
Thanks you so much!

**Comment by wswebcreation** [comment]
Not a problem.

By the way, are you using Protractor? If so,  I've just created a new module called [protractor-multiple-cucumber-html-reporter-plugin](https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin) that makes the integration of this module much easier in your current Protractor project and is also prepared for CucumberJS 3.

Gonna close this issue for now.
