### ISSUE TITLE
PDF format generation

### ISSUE THREAD

**Issue by Phonesis** [wswebcreation/multiple-cucumber-html-reporter#101]
We use this library in Jenkins to generate reports when our tests run in parallel on multiple devices. It is a great format but difficult to share in emails etc. 

Is there any way we can generate the report / convert it into a PDF format? Perhaps this could be added as an option?  We have tried doing it in Chrome via Print - Save As PDF but the formatting becomes very broken.

**Comment by wswebcreation** [comment]
Hi @Phonesis 

No, this is not on the roadmap of this module. If someone wants to add it I'm fine with it 😉
