### ISSUE TITLE
Unable to parse JSON object while attaching Json to a step

### ISSUE THREAD

**Issue by siva1711** [wswebcreation/multiple-cucumber-html-reporter#102]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: [e.g. 1.10.0] - 1.13.0
 - Node.js version: [e.g. 8.9.1] - 10.13.0
 - NPM version: [e.g. 5.8.0] - 6.4.1
 - Platform name and version: [e.g. Windows 10] - Windows 10
 - Cucucmber version: [e.g. 4.2.0] - 5.1.0

**Config of multiple-cucumber-html-reporter**
An example of how you configured the reporter in your config
generate({
            jsonDir: './cucumber-json/',
            reportPath: './cucumber-html/',
        });

**Describe the bug**
When I tried to attach the JSON ({"Sample":2}) to a cucumber report, I am getting 'Unexpected token o in JSON at position 1' error. I am facing this issue with latest changes of the report. I could see the latest refactor changes JSON.parse(embedding.data), where it is trying to convert to a string which in result throwing above mentioned error.

JSON.parse(JSON.stringify(embedding.data)) should be fixing this issue (https://stackoverflow.com/questions/38380462/syntaxerror-unexpected-token-o-in-json-at-position-1/38380728). 

**To Reproduce**
Attach any JSON string in the step. Ex: cucumberJson.attach({"json-string": true}, 'application/json');
[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem. If you don't have log, enable 'debug:true' in the config and paste the log here.
Please use proper markdown to style it

**Additional context**

Please let me know if you need more details

**Comment by siva1711** [comment]
This would also fix my issue if I provide json data as cucumberJson.attach(JSON.stringify({"json-string": true}), 'application/json'); in my code. But this is something we can add to the generate-report.js so that we no need to convert the data in our code.

**Comment by wswebcreation** [comment]
Hi @siva1711 

It has been fixed with this new release https://github.com/wswebcreation/multiple-cucumber-html-reporter/releases/tag/v1.13.1. Can you please update , verify and close the issue if it is fixed for you?

**Comment by siva1711** [comment]
Thanks for the fix @wswebcreation , It is working fine now.

**Comment by wswebcreation** [comment]
Awesome
