### ISSUE TITLE
Can multiple-cucumber-html-reporter support cucumberJs v6 ?

### ISSUE THREAD

**Issue by Zrollan** [wswebcreation/multiple-cucumber-html-reporter#104]
There are breaking changes to the JSON output in the v6 release of cucumber-js, please see here: https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#breaking-changes

Can multiple-cucumber-html-reporter support for the new JSON format ? thank you.

**Comment by izeau** [comment]
FYI they reverted the change made to JSON output 3 days ago, you may use this reporter once you upgrade to cucumber-js ^6.0.3

**Comment by Zrollan** [comment]
Thank you for your remind @izeau , after upgrade to cucumber-js ^6.0.3 this reporter works again!
