### ISSUE TITLE
saveCollectedJson: true - generates this error

### ISSUE THREAD

**Issue by larryg01** [wswebcreation/multiple-cucumber-html-reporter#105]
Hi am using the "saveCollectedJson: true" option and getting this error (see below) when I run the test a second time, the enriched and merged files are being created but its not generating the report

" UnhandledPromiseRejectionWarning: TypeError: JSON.parse(...).map is not a function
at files.map.file (/Users/lgoddard/Projects/klassi-js/node_modules/multiple-cucumber-html-reporter/lib/collect-jsons.js:23:30) "

can you assist please?

NOTE: on first run the report is produced, its on the second run thats when its failing with tha above error

**Comment by wswebcreation** [comment]
Hi @larryg01 

Can you provide a working example so I can debug it for you? I don't have that issue when I run my tests.
