### ISSUE TITLE
If < or > exists in a step name, it is removed from the report HTML

### ISSUE THREAD

**Issue by dawn-minion** [wswebcreation/multiple-cucumber-html-reporter#106]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.13.1
 - Node.js version: v12.13.1
 - Yarn version: 1.19.1
 - Platform name and version: Ubutnu 19.10
 - Cucucmber version: 6.0.5

**Config of multiple-cucumber-html-reporter**
```js
    reporter.generate({
        jsonDir: args.report,
        reportPath: args.output,
        customMetadata: true,
        displayDuration: true
    })
```

**Describe the bug**
We have a step that takes a string argument, and that argument often times has strings like this in it: `<timestamp>`. We use it to parse entries from a text file by searching for the string argument.

However, when we generate the report, the argument is changed to an empty string:
![Screenshot from 2019-11-21 13-38-43](https://user-images.githubusercontent.com/35529725/69338813-41e4d480-0c64-11ea-9652-45ef29702e29.png)

**To Reproduce**
Here is an example report I used to generate the above screenshot:
```json
[
  {
    "keyword": "Feature",
    "name": "Test",
    "line": 1,
    "id": "test",
    "tags": [],
    "uri": "features/test.feature",
    "elements": [
      {
        "id": "test;wait-for-2-seconds",
        "keyword": "Scenario",
        "line": 2,
        "name": "Wait for 2 seconds",
        "tags": [],
        "type": "scenario",
        "steps": [
          {
            "arguments": [],
            "keyword": "Given ",
            "line": 3,
            "name": "we look for this text in the file \"<myTest>\"",
            "match": {
              "location": "features/steps/test.js:7"
            },
            "result": {
              "status": "passed",
              "duration": 0
            }
          }
        ]
      }
    ]
  }
]
```

**Expected behavior**
I would expect "<myTest>" to appear in the report, and not an empty string. It's a bit confusing to have it stripped out, as the report does not match the actual step run.

**Comment by dawn-minion** [comment]
Looking at the output, it seems the browser interprets it as a tag, causing it not to be shown. Here's the above report:
![Screenshot from 2019-11-21 13-46-08](https://user-images.githubusercontent.com/35529725/69339338-642b2200-0c65-11ea-8fc2-9d86b3293fd6.png)

**Comment by wswebcreation** [comment]
@dawn-minion 

Can you please verify it with https://github.com/wswebcreation/multiple-cucumber-html-reporter/releases/tag/v1.13.2?

**Comment by dawn-minion** [comment]
@wswebcreation Will do this morning, thanks for releasing it

**Comment by dawn-minion** [comment]
Just tried the release, works great.

**Comment by wswebcreation** [comment]
Awesome, thanks for your time!
