### ISSUE TITLE
Show duration

### ISSUE THREAD

**Issue by AnandGanesh-Reflektion** [wswebcreation/multiple-cucumber-html-reporter#11]
It would be great if the report can show duration at step, scenario and feature levels.
Other reports provide the facility to show the duration. This helps to evaluate the performance of api/ui.

**Comment by wswebcreation** [comment]
Hi @AnandGanesh-Reflektion 

That would be nice. I had it when I was developing it but I removed it when I saw that it didn't gave good results. With good I mean that for example UI testing a complete scenario, according to CucumberJS took 8 seconds, the test itself (including creating and tearing down the browser) took almost 30 seconds. 

But if you want to create a PR for it, feel free

**Comment by LennDG** [comment]
I have recently encountered a use case that needs this. I will create a PR somewhere next week that will add functionality that lets you toggle duration display. 

Cucumber reports duration per step, I will add a total time to the feature index page (total duration of feature) and a duration per scenario in the feature overview page.

**Comment by wswebcreation** [comment]
@LennDG 

Tnx, that would be nice. Please check that it gives the correct results in Cucumber 2 and 3. I know there was some difference in the time notation in the report between those versions

**Comment by LennDG** [comment]
Do you have any idea how to determine cucumber version from the report? Or should I just give it as an option to set?

**Comment by wswebcreation** [comment]
Hi @LennDG 

Sorry for my late reaction. I've checked it and there is not a difference in CucumberJS 2 and 3 but version 1 and 2, see the time in version [1](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/master/test/unit/data/json/happy_flow_v1.json#L26) and version [2](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/master/test/unit/data/json/happy_flow_v2.json#L68). I can't find the change in the changelog, but version 1 does it in nanoseconds and 2 in milliseconds.

The version is also not provided in the report. For now we can just use milliseconds. That means that reports from version 1 will show the incorrect version, but the amount of people that are on version 1 should be lower the on version 2,3 and 4.

Hope this helps

**Comment by LennDG** [comment]
[PR created](https://github.com/wswebcreation/multiple-cucumber-html-reporter/pull/28). I did not add the time to the overview page because I could not figure out a nice place to put it.

**Comment by wswebcreation** [comment]
PR has been merged and a new release is made. Tnx @LennDG !!
