### ISSUE TITLE
Feature/Scenario name without tags

### ISSUE THREAD

**Issue by lind-eduard** [wswebcreation/multiple-cucumber-html-reporter#110]
**Describe your question with as much detail as possible**
Hi, is it possible to see feature/scenario name without tags there? In general to show tags is a great idea, but maybe we can somehow exclude them from names?

**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.13.0
 - Node.js version: 10.16.3
 - Platform name and version: Windows 10
 - Cucucmber version: 4.0.7

**Additional context**
![2020-02-12_17h32_47](https://user-images.githubusercontent.com/58471287/74356154-29e1a480-4dbe-11ea-9898-d4585e875dcf.png)
![2020-02-12_17h32_55](https://user-images.githubusercontent.com/58471287/74356157-2a7a3b00-4dbe-11ea-8835-9d42c8e8d5d2.png)

**Comment by wswebcreation** [comment]
Hi @lind-eduard 

This is likely not an issue with the module but with the data you are sending to the module, meaning it's already in your Feature/Scenario description in the JSON file.
Can you post your JSON file here so we can verify that?

**Comment by lind-eduard** [comment]
@wswebcreation , you're right, I just checked JSON file and I see there name of feature with tag already.  I would be very appreciated if can give me a hint how to exclude tag from name for json, if you had similar experience, other than that, we can close this.
Thanks for answer!

**Comment by wswebcreation** [comment]
Which testframework are you using?

(Closing it now)

**Comment by lind-eduard** [comment]
I'm using wdio-cucumberjs-json-reporter(https://www.npmjs.com/package/wdio-json-cucumber-reporter) to generate json. So general setup is WebdriverIO + Cucumber

**Comment by wswebcreation** [comment]
@lind-eduard 

With which version of WDIO? This version for V5 also supports the missing features which are mentioned in the reporter you are using https://webdriver.io/docs/wdio-cucumberjs-json-reporter.html

**Comment by lind-eduard** [comment]
Wdio version is 5.18.6(latest I think), just in case cucumber version is 4.07.

**Comment by wswebcreation** [comment]
Cucumber will be provided by the cucumber framework which will be 5 ai think, so if you have it as a dependency you can remove it
