### ISSUE TITLE
Question: can I insert a link at the header of footer of the at per feature level?

### ISSUE THREAD

**Issue by xywang68** [wswebcreation/multiple-cucumber-html-reporter#115]
Hi:

I have a run log in html forms for each feature run, which includes all the scenarios in this feature.
I would like to attach the run log html in html link for each feature. It can be at either before all the scenarios in this feature, or after.

my tag would look like
<a href="relativePath/myfeatureOne.log.html>myfeatureOne.log</a>

Is there a way I can insert such tag?

**Comment by wswebcreation** [comment]
Currently this module doesn't support that, but I'm open for a PR

**Comment by Anupku77** [comment]
Do we have any update on this?

**Comment by BaCaRoZzo** [comment]
@Anupku77 [`plainDescription`](https://github.com/wswebcreation/multiple-cucumber-html-reporter#plaindescription) was recently added to allow for custom formatted `description` fields. I believe the OP use case can be covered by that. Or, at least, `plainDescription` allow for a lot of wiggling room when it comes to what it can be inserted there. See the documentation.

**Comment by wswebcreation** [comment]
Closing this now due to inactivity
