### ISSUE TITLE
Report Generate error

### ISSUE THREAD

**Issue by tech-dragon157** [wswebcreation/multiple-cucumber-html-reporter#117]
I have a large test run and some of the tests do not have results in the json report.

the report generate is failing, I think due to this line

https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/c5e6ebd117f55e5949f946697060cc935496cebf/templates/components/scenarios.tmpl#L84

Get an error like can't get `status` from undefined. Is this something that can be resolved?

**Comment by wswebcreation** [comment]
@tech-dragon157 

Can you please provide more information like:
- which framework are you using in combination with Cucumber
- an example json file

It's hard to debug in this way

Thanks

**Comment by tech-dragon157** [comment]
we are using Nightwatch / cucumber running on selenium grid.

nightwatch: "1.3.4",
nightwatch-api: "3.0.1"
cucumber: "6.0.3"

the output is here, its large, but is the sort of thing we need to be working [https://raw.githubusercontent.com/tech-dragon157/nightwatch/master/cucumber_report_2020-04-22T122051%2B606223080.json](https://raw.githubusercontent.com/tech-dragon157/nightwatch/master/cucumber_report_2020-04-22T122051%2B606223080.json)

**Comment by wswebcreation** [comment]
@tech-dragon157 
Can you please check with https://github.com/wswebcreation/multiple-cucumber-html-reporter/releases/tag/v1.16.2, it should be fixed now
