### ISSUE TITLE
Report does not show if the feature file is passed with retry logic

### ISSUE THREAD

**Issue by pradeepnyk** [wswebcreation/multiple-cucumber-html-reporter#118]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.16.0
 - Node.js version: 12.15.0
 - NPM version: 6.14.2
 - Platform name and version: Windows 10
 - Cucucmber version: 5.18.6

**Config of multiple-cucumber-html-reporter**
```js
reporters: ['spec', ['cucumberjs-json', {
        jsonFolder: 'test-reports/mobile/radio/cucumber-report/',
        language: 'en'
    }
    ]],
onPrepare: function (config, capabilities) {
        removeSync('test-reports/mobile/radio/');
    },
onComplete: function (exitCode, config, capabilities, results) {
        generate({
            jsonDir: './test-reports/mobile/radio/cucumber-report',
            reportPath: './test-reports/mobile/radio/generated-report/',
            openReportInBrowser: false,
            displayDuration: true
        });
    },
```

**Describe the bug**
Cucumber report html file does not show any indication if a feature file got passed with a retry logic by using: `specFileRetries: 1,` in my config file which drives WebdriverIO test runner

**To Reproduce**
1. Create a feature file and use that feature file to run the test using the above config to generate report
2. Make sure `specFileRetries: 1,` is added in the config file
3. Simulate the run so that it will fail in the 1st attempt, and because of the above property value, test will run again, and it will pass
4. Observe the 1st feature is failed & 2nd feature is passed, where as there is only 1 feature file to run.'

[Include code or an example repository that can easily be set up]

**Expected behavior**
Here, I will expect another column in the report to say retry is 'true' & there will only be 1 feature executed with status 'PASS

**Log**
If applicable, add logs to help explain your problem. If you don't have log, enable 'debug:true' in the config and paste the log here.
Please use proper markdown to style it

**Additional context**

**Comment by wswebcreation** [comment]
@pradeepnyk 

Thanks for filing a ticket here, as fas as I can see it: 
- this is not something in this module specifically, but in the https://github.com/wswebcreation/wdio-cucumberjs-json-reporter module that generates the json file-, please file a ticket there and provide a sample repo where you explain the issue
- if the module supports retries then this is a feature request for this module, which is, as far as I know, an official feature of CucumberJs itself

Going to close it for now because of the following above points
