### ISSUE TITLE
After Features hook

### ISSUE THREAD

**Issue by thomas-dowling** [wswebcreation/multiple-cucumber-html-reporter#12]
Hi, 
I have this AfterFeatures hook but it isn't displaying any report..

![image](https://user-images.githubusercontent.com/25334765/31114760-85e322d0-a817-11e7-89d8-c7890b9ae479.png)

Any idea why?

**Comment by wswebcreation** [comment]
Is the console log printed? If not, then it could be that the hook is not loaded in your config

**Comment by thomas-dowling** [comment]
Thanks for the quick reply :). No it isn't, do you use the same Hook? If you could forward me to a working example I would be grateful

**Comment by thomas-dowling** [comment]
I do have hooks stated in my config. I'm using a version of Cucumber called Nightwatch-cucumber

**Comment by thomas-dowling** [comment]
![image](https://user-images.githubusercontent.com/25334765/31114934-3df71368-a818-11e7-940e-736890511a0f.png)

**Comment by wswebcreation** [comment]
I never used Nightwatch-cucumber so I can't help you with that. Which version of Cucumber are you using? I normally use Protractor and I used this with CucumberJS 2 (https://github.com/wswebcreation/protractor-cucumber-typescript-boilerplate/blob/2.x/e2e-tests/config/helpers/reporter.ts)

The fact that the hook is not loaded has nothing to do with this module, so I'm going to close the issue. It's still open for discussion.
