### ISSUE TITLE
"metadata" when passed to generate method in webdriverio config is not considered while Report Generation

### ISSUE THREAD

**Issue by rajatpuneak** [wswebcreation/multiple-cucumber-html-reporter#121]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.16.2
 - Node.js version: 12.14.1
 - NPM version: 6.13.4
 - Platform name and version: Mac OSX Catalina
 - Cucucmber version: @wdio/cucumber-framework": "^6.1.8"

**Describe the bug**
passing metadata while report generation, and its not showing up in the report
![image](https://user-images.githubusercontent.com/10356755/82625690-77627e80-9c03-11ea-9fdf-3ccf794b3925.png)

gives metadata not available, version not known in report.

**Config of multiple-cucumber-html-reporter**
```
const { generate } = require('multiple-cucumber-html-reporter');

    onComplete: function (exitCode, config, capabilities, results) {
        generate({
            theme: 'bootstrap',
            jsonDir: './tests/reports/json',
            reportPath: './tests/reports/html',
            openReportInBrowser: true,
            // disableLog: true,
            displayDuration: true,
            metadata: {
            metadata: {
                // for an app
                app: {
                    name: "test App",
                    version: '1.2.3',
                },
                device: "iPhone X",
                platform: {
                    name: "iOS",
                    version: "13.0"
                }
            },
            pageTitle: "Test Report
}
```

**Additional context**
Using this as reporter in WebDriverIO v6,
with cucumber json generated by : 'wdio-cucumberjs-json-reporter'

**Comment by wswebcreation** [comment]
@rajatpuneak 

Thanks for filing an issue here, but the module for WebdriverIO handles the meta-data out of the box for you, you can provide it as this https://github.com/wswebcreation/wdio-cucumberjs-json-reporter#metadata

If there is an issue with that please file it there. Closing this one for now.
