### ISSUE TITLE
multiple-cucumber-html-reporter doesn't report variables in dataTables from Scenarios Outline Examples #5434

### ISSUE THREAD

**Issue by JuanRodriguezAbarca** [wswebcreation/multiple-cucumber-html-reporter#124]
There is an issue parsing variable values from Examples in Scenario Outline to the Json Reporter in data tables
 See the report:
![image](https://user-images.githubusercontent.com/11064158/82906134-15887880-9f65-11ea-8dd5-7dd2684e9128.png)
And the feature:
![image](https://user-images.githubusercontent.com/11064158/82905664-6f3c7300-9f64-11ea-9a23-3e36736ceb41.png)
![image](https://user-images.githubusercontent.com/11064158/82906451-90519380-9f65-11ea-8c4b-0dd233cd2a0b.png)

The execution is ok, the problem happens when parsing the variable. See the json report block:
```
"cells": [
                                            "<name>",
                                            "<description>",
                                            "<accountPlan>",
                                            "<API>",
                                            "<environment>",
                                            ""
                                        ],

```
Which is taken in the html as html nodes because the '<>; symbols

My npm dependencies:
"devDependencies": {
    "@babel/cli": "7.8.4",
    "@babel/core": "7.9.0",
    "@babel/preset-env": "^7.9.6",
    "@babel/register": "^7.7.0",
    "@wdio/cucumber-framework": "6.1.13",
    "@wdio/local-runner": "5.23.0",
    "@wdio/spec-reporter": "5.23.0",
    "@wdio/sync": "5.23.0",
    "chromedriver": "^83.0.0",
    "expect": "24.3.0",
    "expect-webdriverio": "0.2.0",
    "fs-extra": "^9.0.0",
    "geckodriver": "^1.19.1",
    "multiple-cucumber-html-reporter": "^1.16.2",
    "wdio-chromedriver-service": "5.0.2",
    "wdio-cucumberjs-json-reporter": "^2.0.0",
    "wdio-geckodriver-service": "^1.0.3",
    "winston": "^3.2.1",
    "yargs": "^15.3.1"

**Comment by wswebcreation** [comment]
@JuanRodriguezAbarca 

Please file it to the correct project, see my comment https://github.com/webdriverio/webdriverio/issues/5434#issuecomment-634046879 and please provide the json file
