### ISSUE TITLE
Question: Can I create individual reports for each browser that I've used ? 

### ISSUE THREAD

**Issue by arcanum0** [wswebcreation/multiple-cucumber-html-reporter#125]
During report generation I want something like this :
reports/Firefox/firefox_reports.json
reports/Chrome/chrome_reports.json

Each browsers is running same set of feature files and then I would want create html reports and store then inside the appropriate folder , like this: 
reports/Firefox/firefox_reports.html
reports/Chrome/chrome_reports.html

Can someone guide me how to do so ?

**Comment by wswebcreation** [comment]
Hi @arcanum0 

What framework are you using to execute the tests? Reason for asking is that the framework needs to handle this, this is not something this module can do. This module will only process the data that it has been giving, it can't modify the names of the files because it doesn't have a clue on which browser they were ran.

Going to close it for now because it's not an issue but it's still open for discussion

**Comment by arcanum0** [comment]
Hi @wswebcreation 

I'm using protractor with cucumber. I'm trying to create separate report for each browser executing same set of feature files.

If that won't be possible I'm trying to replicate [this](https://wswebcreation.github.io/multiple-cucumber-html-reporter/browsers/index.html) instead.

I'm using multicapabilites along with shardTestFiles=true. So if I'm using 2 feature files and running them on firefox and chrome , four json reports are created. HTML report generation is done in afterLaunch(),  taking all json files and generating index.html but there is no browser information shown. 

JSON reports also don't have any information on browser used, can you guide me what to do so that index.html also shows which browser does the feature file was run upon.

**Comment by wswebcreation** [comment]
@arcanum0 

Have you tried using this module https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin. It's a module that will create separate files per instance/ It was also my module, but I deprecated it due to the fact that Protractor is dead

**Comment by desaijay315** [comment]
Hi @wswebcreation/ @arcanum0  , I am not using the protractor plugin and the package, I am using cucumber and cucumber-preprocessor-plugin, 
Currently, the metadata only supports single browser, Can this package help us to generate multiple browser report. I am also trying for the same - [Link](https://wswebcreation.github.io/multiple-cucumber-html-reporter/browsers/index.html)

**Comment by wswebcreation** [comment]
@desaijay315 

This module can only translate the data that is provided to a HTML report. It doesn't have the context of which browser executed which test. That needs to be added by the framework that tis running the test

**Comment by desaijay315** [comment]
Hi @wswebcreation , 
Do we have any example for the cucumber or cypress framework integration with this package which can showcase the same  [Link](https://wswebcreation.github.io/multiple-cucumber-html-reporter/browsers/index.html). ?

**Comment by wswebcreation** [comment]
Hi @desaijay315 

No, we currently don't have it, feel free to open a PR to add it here
