### ISSUE TITLE
Background tasks are considered as scenarios

### ISSUE THREAD

**Issue by Apolayo27** [wswebcreation/multiple-cucumber-html-reporter#126]
![image](https://user-images.githubusercontent.com/44474459/83822537-eecdee80-a696-11ea-89eb-f5155e87b9e9.png)

**Comment by wswebcreation** [comment]
Hi @Apolayo27 

Can you please provide a sample JSON file, the previous issue was closed and I didn't had enough time to look at it.

**Comment by Apolayo27** [comment]
> Hola @ Apolayo27
> 
> ¿Puede proporcionar un archivo JSON de muestra? El problema anterior se cerró y no tuve tiempo suficiente para mirarlo.

[
  {
    "line": 2,
    "elements": [
      {
        "line": 4,
        "name": "Ambientes y navegador",
        "description": "",
        "type": "background",
        "keyword": "Antecedentes",
        "steps": [
          {
            "result": {
              "duration": 42704000,
              "status": "passed"
            },
            "line": 5,
            "name": "que el ambiente escogido es \"local\"",
            "match": {
              "arguments": [
                {
                  "val": "\"local\"",
                  "offset": 28
                }
              ],
              "location": "steps.preconditions.queElAmbienteEscogidoEs(java.lang.String)"
            },
            "keyword": "Dado "
          },
          {
            "result": {
              "duration": 1416368000,
              "status": "passed"
            },
            "line": 6,
            "name": "se muestre el explorador será \"chrome\"",
            "match": {
              "arguments": [
                {
                  "val": "\"chrome\"",
                  "offset": 30
                }
              ],
              "location": "steps.preconditions.seMuestreElExploradorSerá(java.lang.String)"
            },
            "keyword": "Cuando "
          }
        ]
      },
      {
        "start_timestamp": "2020-06-05T22:53:40.550Z",
        "line": 9,
        "name": "AUT - Como cliente de BG quiero solicitar una póliza de vida con cuatro beneficiarios",
        "description": "",
        "id": "datos-en-pantalla-de-aceptación;aut---como-cliente-de-bg-quiero-solicitar-una-póliza-de-vida-con-cuatro-beneficiarios",
        "type": "scenario",
        "keyword": "Escenario",
        "steps": [
          {
            "result": {
              "duration": 3599209000,
              "status": "passed"
            },
            "line": 10,
            "name": "el \"cliente con cuenta\" selecciona el botón \"¡Quiero un seguro de vida!\"",
            "match": {
              "arguments": [
                {
                  "val": "\"cliente con cuenta\"",
                  "offset": 3
                },
                {
                  "val": "\"¡Quiero un seguro de vida!\"",
                  "offset": 44
                }
              ],
              "location": "steps.landing.elSeleccionaElBotón(java.lang.String,java.lang.String)"
            },
            "keyword": "Dado "
          },
          {
            "result": {
              "duration": 189910000,
              "status": "passed"
            },
            "line": 11,
            "name": "selecciona el \"Plan A\"",
            "match": {
              "arguments": [
                {
                  "val": "\"Plan A\"",
                  "offset": 14
                }
              ],
              "location": "steps.plans.seleccionaEl(java.lang.String)"
            },
            "keyword": "Y "
          },
          {
            "result": {
              "duration": 143105000,
              "status": "passed"
            },
            "line": 12,
            "name": "\"acepta\" la declaración de salud",
            "match": {
              "arguments": [
                {
                  "val": "\"acepta\"",
                  "offset": 0
                }
              ],
              "location": "steps.declaration.laDeclaraciónDeSalud(java.lang.String)"
            },
            "keyword": "Y "
          },
          {
            "result": {
              "duration": 335194000,
              "status": "passed"
            },
            "line": 13,
            "name": "hace clic en el botón \"Siguiente\"",
            "match": {
              "arguments": [
                {
                  "val": "\"Siguiente\"",
                  "offset": 22
                }
              ],
              "location": "steps.acceptance.haceClicEnElBotón(java.lang.String)"
            },
            "keyword": "Y "
          },
          {
            "result": {
              "duration": 6398646000,
              "status": "passed"
            },
            "line": 14,
            "name": "agrega los beneficiarios:",
            "match": {
              "location": "steps.beneficiaries.agregaLosBeneficiarios(io.cucumber.datatable.DataTable)"
            },
            "rows": [
              {
                "cells": [
                  "nombre",
                  "cedula",
                  "parentesco"
                ]
              },
              {
                "cells": [
                  "Miguel",
                  "8-811-1888",
                  "PRIMO"
                ]
              },
              {
                "cells": [
                  "Glendy",
                  "8-988-755",
                  "SOBRINO"
                ]
              },
              {
                "cells": [
                  "Cecilia",
                  "8-877-544",
                  "ABUELO"
                ]
              },
              {
                "cells": [
                  "Claudia",
                  "8-145-755",
                  "MADRE"
                ]
              }
            ],
            "keyword": "Y "
          },
          {
            "result": {
              "duration": 216413000,
              "status": "passed"
            },
            "line": 20,
            "name": "hace clic en el botón \"Siguiente\"",
            "match": {
              "arguments": [
                {
                  "val": "\"Siguiente\"",
                  "offset": 22
                }
              ],
              "location": "steps.acceptance.haceClicEnElBotón(java.lang.String)"
            },
            "keyword": "Y "
          },
          {
            "result": {
              "duration": 223922000,
              "status": "passed"
            },
            "line": 21,
            "name": "\"acepta\" el porcentaje calculado haciendo clic en el botón \"Siguiente\"",
            "match": {
              "arguments": [
                {
                  "val": "\"acepta\"",
                  "offset": 0
                },
                {
                  "val": "\"Siguiente\"",
                  "offset": 59
                }
              ],
              "location": "steps.porcentages.elPorcentajeCalculadoHaciendoClicEnElBotón(java.lang.String,java.lang.String)"
            },
            "keyword": "Y "
          },
          {
            "result": {
              "duration": 4027270000,
              "status": "passed"
            },
            "line": 22,
            "name": "selecciona la opción \"Cargo automático a mi cuenta\" escogiendo la \"primera\" de la lista",
            "match": {
              "arguments": [
                {
                  "val": "\"Cargo automático a mi cuenta\"",
                  "offset": 21
                },
                {
                  "val": "\"primera\"",
                  "offset": 66
                }
              ],
              "location": "steps.payment.seleccionaLaOpciónEscogiendoLaDeLaLista(java.lang.String,java.lang.String)"
            },
            "keyword": "Cuando "
          },
          {
            "result": {
              "duration": 516649000,
              "status": "passed"
            },
            "line": 23,
            "name": "\"acepta\" la declaración de débitos automáticos haciendo clic en el botón \"Aceptar\" del popup",
            "match": {
              "arguments": [
                {
                  "val": "\"acepta\"",
                  "offset": 0
                },
                {
                  "val": "\"Aceptar\"",
                  "offset": 73
                }
              ],
              "location": "steps.payment.laDeclaraciónDeDébitosAutomáticosHaciendoClicEnElBotónDelPopup(java.lang.String,java.lang.String)"
            },
            "keyword": "Y "
          },
          {
            "result": {
              "duration": 205658000,
              "status": "passed"
            },
            "line": 24,
            "name": "hace clic en el botón \"Siguiente\"",
            "match": {
              "arguments": [
                {
                  "val": "\"Siguiente\"",
                  "offset": 22
                }
              ],
              "location": "steps.acceptance.haceClicEnElBotón(java.lang.String)"
            },
            "keyword": "Y "
          },
          {
            "result": {
              "duration": 484726000,
              "status": "passed"
            },
            "line": 25,
            "name": "se muestra la pantalla de \"Aceptación\" con \"cuatro beneficiarios\"",
            "match": {
              "arguments": [
                {
                  "val": "\"Aceptación\"",
                  "offset": 26
                },
                {
                  "val": "\"cuatro beneficiarios\"",
                  "offset": 43
                }
              ],
              "location": "steps.acceptance.seMuestraLaPantallaDeCon(java.lang.String,java.lang.String)"
            },
            "keyword": "Entonces "
          },
          {
            "result": {
              "duration": 153461000,
              "status": "passed"
            },
            "line": 26,
            "name": "hace clic en el botón \"Comprar seguro de vida\"",
            "match": {
              "arguments": [
                {
                  "val": "\"Comprar seguro de vida\"",
                  "offset": 22
                }
              ],
              "location": "steps.acceptance.haceClicEnElBotón(java.lang.String)"
            },
            "keyword": "Y "
          },
          {
            "result": {
              "duration": 330316000,
              "status": "passed"
            },
            "line": 27,
            "name": "se muestra la pantalla \"Felicidades\" con la información de la poliza adquirida",
            "match": {
              "arguments": [
                {
                  "val": "\"Felicidades\"",
                  "offset": 23
                }
              ],
              "location": "steps.congratulations.seMuestraLaPantallaConLaInformaciónDeLaPolizaAdquirida(java.lang.String)"
            },
            "keyword": "Y "
          }
        ],
        "tags": [
          {
            "name": "@TEST_PDVS-286"
          },
          {
            "name": "@smoke-test"
          },
          {
            "name": "@complete"
          },
          {
            "name": "@RC-HP"
          },
          {
            "name": "@WIP"
          }
        ]
      }
    ],
    "name": "Datos en Pantalla de Aceptación",
    "description": "",
    "id": "datos-en-pantalla-de-aceptación",
    "keyword": "Característica",
    "uri": "file:src/test/java/features/cliente_con_cuenta/aceptacion_solicitud_4beneficiarios.feature",
    "tags": []
  }
]

**Comment by kontownik** [comment]
I could confirm the issue using multiple-cucumber-html-reporter@1.16.3 with json generated by cucumber-java:6.1.2

Added JSON used and comparison between multiple-cucumber-html-reporter and cucumber pretty-html plugin.

<img width="1672" alt="github_1" src="https://user-images.githubusercontent.com/3976951/87004318-87d3b600-c1bd-11ea-8552-f95bb76f9f24.png">
`[
    {
        "metadata": {
            "device": "Xiaomi Mi A2 Lite",
            "platform": {
                "name": "android",
                "version": "9"
            }
        },
        "line": 2,
        "elements": [
            {
                "line": 4,
                "name": "",
                "description": "",
                "type": "background",
                "keyword": "Background",
                "steps": [
                    {
                        "result": {
                            "duration": 110000000,
                            "status": "passed"
                        },
                        "line": 5,
                        "name": "I accepted all the required app permissions",
                        "match": {
                            "location": "void mastestproject.steps.BasicSteps.acceptAllPermissions()"
                        },
                        "keyword": "Given "
                    },
                    {
                        "result": {
                            "duration": 9727000000,
                            "status": "passed"
                        },
                        "line": 6,
                        "name": "I accepted Eula",
                        "match": {
                            "location": "void mastestproject.steps.AcceptEulaSteps.acceptedEula()"
                        },
                        "keyword": "And "
                    },
                    {
                        "result": {
                            "error_message": "dummy",
                            "duration": 32309000000,
                            "status": "failed"
                        },
                        "line": 7,
                        "name": "abcd",
                        "match": {
                            "arguments": [
                                {
                                    "val": "a",
                                    "offset": 5
                                },
                                {
                                    "val": "b",
                                    "offset": 26
                                },
                                {
                                    "val": "c",
                                    "offset": 45
                                },
                                {
                                    "val": "d",
                                    "offset": 67
                                }
                            ],
                            "location": "java class"
                        },
                        "keyword": "And "
                    }
                ]
            },
            {
                "start_timestamp": "2020-07-09T06:02:45.958Z",
                "line": 10,
                "name": "Auto launch (RO)",
                "description": "",
                "id": "auto-launch;auto-launch-(ro)",
                "after": [
                    {
                        "embeddings": [
                            {
                                "data": "screenshot data here",
                                "mime_type": "image/png",
                                "name": "Error screenshot"
                            }
                        ],
                        "result": {
                            "duration": 3182000000,
                            "status": "passed"
                        },
                        "match": {
                            "location": "void mastestproject.steps.CucumberHooks.afterScenario(io.cucumber.java.Scenario)"
                        }
                    }
                ],
                "type": "scenario",
                "keyword": "Scenario",
                "steps": [
                    {
                        "result": {
                            "status": "skipped"
                        },
                        "line": 11,
                        "name": "I run app2app or Safari",
                        "match": {
                            "location": "void mastestproject.steps.App2AppSteps.runApp2App()"
                        },
                        "keyword": "Given "
                    },
                    {
                        "result": {
                            "status": "skipped"
                        },
                        "line": 12,
                        "name": "The view is app2app or Safari",
                        "match": {
                            "location": "void mastestproject.steps.App2AppSteps.validateIfApp2AppVisible()"
                        },
                        "keyword": "And "
                    },
                    {
                        "result": {
                            "status": "skipped"
                        },
                        "line": 13,
                        "name": "dummy abc",
                        "match": {
                            "arguments": [
                                {
                                    "val": "a",
                                    "offset": 15
                                },
                                {
                                    "val": "b",
                                    "offset": 33
                                },
                                {
                                    "val": "c",
                                    "offset": 59
                                }
                            ],
                            "location": "void mastestproject.steps.App2AppSteps.enterScheme(java.lang.String,java.lang.String,java.lang.String)"
                        },
                        "keyword": "When "
                    },
                    {
                        "result": {
                            "status": "skipped"
                        },
                        "line": 14,
                        "name": "I execute Autolaunch command",
                        "match": {
                            "location": "void mastestproject.steps.App2AppSteps.executeApp2AppCommand()"
                        },
                        "keyword": "And "
                    },
                    {
                        "result": {
                            "status": "skipped"
                        },
                        "line": 15,
                        "name": "The view is OTP Result",
                        "match": {
                            "location": "void mastestproject.steps.OTPSteps.verifyOtpResultHeaderTitleIsShowing()"
                        },
                        "keyword": "And "
                    },
                    {
                        "result": {
                            "status": "skipped"
                        },
                        "line": 16,
                        "name": "I go back",
                        "match": {
                            "location": "void mastestproject.steps.BasicSteps.goBack()"
                        },
                        "keyword": "And "
                    },
                    {
                        "result": {
                            "status": "skipped"
                        },
                        "line": 17,
                        "name": "The view is Main page",
                        "match": {
                            "location": "void mastestproject.steps.ActivationSteps.verifyActionsViewIsShowing()"
                        },
                        "keyword": "Then "
                    }
                ],
                "tags": [
                    {
                        "name": "@REGRESSION_AUTO_LAUNCH"
                    },
                    {
                        "name": "@REGRESSION_2"
                    },
                    {
                        "name": "@REGRESSION_3"
                    },
                    {
                        "name": "@AUTO_LAUNCH"
                    }
                ]
            }
        ],
        "name": "Auto launch",
        "description": "",
        "id": "auto-launch",
        "keyword": "Feature",
        "uri": "classpath:features/Autolaunch.feature",
        "tags": [
            {
                "name": "@REGRESSION_AUTO_LAUNCH",
                "location": {
                    "line": 1,
                    "column": 1
                },
                "type": "Tag"
            }
        ]
    }
]`

**Comment by wswebcreation** [comment]
@Apolayo27 and @kontownik 

How would you like to see this handled by the report, based on what we get in the JSON is that the feature will hold and array of "elements", in both examples 1 "element" is the background task and 1 element is the actual feature

**Comment by wswebcreation** [comment]
@Apolayo27 ontownik and @josbeja 

Is this what you are looking for? This will add the before and after-hooks, which are reported differently in Java (on the feature level) in the scenario and it will report the Background also as a background instead of a scenario

![image](https://user-images.githubusercontent.com/11979740/87251064-4d8e4100-c469-11ea-965d-1541db23cd35.png)

If you agree I can fix it and make a new release in the coming days

**Comment by wswebcreation** [comment]
I've release https://github.com/wswebcreation/multiple-cucumber-html-reporter/releases/tag/v1.17.0

**Comment by kontownik** [comment]
now it is working correctly thanks @wswebcreation :)

**Comment by wswebcreation** [comment]
@kontownik 
Thanks for the update!
