### ISSUE TITLE
Need a way to show all the scenarios under a particular feature if the scenarios fall under same feature name

### ISSUE THREAD

**Issue by jaydeepqa** [wswebcreation/multiple-cucumber-html-reporter#127]
Consider, I am having 2 feature files each having 1 scenario which have same feature name but as both are under different feature file hence in report it appears as 2 features but as I have the same feature name in both files, hence I want the report to show one feature only.
Is that possible by any way..request your input.

**Comment by wswebcreation** [comment]
Hi @jaydeepqa 

This report only translates the JSON files it gets provided to a HTML report. As long as they are reported as 2 different feature files in the JSON it will be handled as 2 different features. This means you need to handle this from within your framework.
