### ISSUE TITLE
Hide Metadata in feature Overview table

### ISSUE THREAD

**Issue by sachinArya** [wswebcreation/multiple-cucumber-html-reporter#132]
Is it possible to hide the metadata like "Device", "OS", "Browser", etc. from the feature overview table. I am currently using below configuration

` const { generate } = require("multiple-cucumber-html-reporter");
    //const { removeSync } = require("fs-extra");

    generate({
        // Required
        // This part needs to be the same path where you store the JSON files
        // default = '.tmp/json/'
        jsonDir: "jsonReports/jsonResults/",
        reportPath: "jsonReports/HTMLReports/",
        pageTitle: "LBG Test Report",
        reportName: "<h3 style=\"color:black;\">LBG Test Report</h3>",
        displayDuration:true,
        durationInMS:true
        // for more options see https://github.com/wswebcreation/multiple-cucumber-html-reporter#options
    });
`

**Comment by wswebcreation** [comment]
Hi @sachinArya 

I've released a new version, see https://github.com/wswebcreation/multiple-cucumber-html-reporter/releases/tag/v1.18.0. There you have the option to hide the meta data.

Closing it for now
