### ISSUE TITLE
How to disable showing Before hook and After hook from reports

### ISSUE THREAD

**Issue by qburst-hari** [wswebcreation/multiple-cucumber-html-reporter#137]
**Describe your question with as much detail as possible**
Currently My report shows "Before Hook" and "After Hook" for every scenario, how can I disable it.

**Environment (please complete the following information):**
-multiple-cucumber-html-reporter:1.17.0
-Node.js version: 12.0
-NPM version: 6.14
-Platform name and version:Ubuntu
-Cucucmber version: 6.0.5

**Comment by wswebcreation** [comment]
Hi @qburst-hari 

This is currently not possible, the https://github.com/wswebcreation/wdio-cucumberjs-json-reporter creates this based on WebdriverIO

**Comment by qburst-hari** [comment]
Got it @wswebcreation. Thanks

**Comment by bhaslamb** [comment]
this is done in wdio-cucumberjs-json-reporter module, please download 4.3.0 and add a property call disableHooks:true, which will disable the hooks information
