### ISSUE TITLE
Request for new enhancement to Report like customized titles for this Report like Project Name, Release name and Cycle name and execution start & end time along with timezone

### ISSUE THREAD

**Issue by Sanj2005** [wswebcreation/multiple-cucumber-html-reporter#14]
Hi - This report is really great. I was wondering if we can have additional details on the Report like below

- Project/Application Name:  'XYZ Automation',
- Release Name: 'ABC',
- Cycle Name: '2',
- Execution Start Time: Nov 13th 2017, 02:31 PM EST
- Execution End Time: Nov 13th 2017, 02:56 PM EST

User should be allowed to pass this data as below

```js
const report = require('multiple-cucumber-html-reporter');
report.generate({
      automaticallyGenerateReport: true,
      removeExistingJsonReportFile: true,
      removeOriginalJsonReportFile: true,
      openReportInBrowser: true,
      saveCollectedJSON: true,
      jsonOutputPath: './reports/report-plugin-json-output-folder/',
      reportPath: './reports/protractor-multiple-cucumber-html-report/',
      disableLog: false,
      metadataKey: 'deviceProperties',
      Project/Application Name : 'XYZ Automation',
      Release Name: 'ABC',
      Cycle  : '2',
      ShowExecutionTimeFlag: true  
      customizedReportName : 'Multi Browser Protractor Cucumber HTML Report'
});
```
Also if possible customized name for the Report file as mentioned above - customizedReportName 

Thanks

**Comment by wswebcreation** [comment]
Hi @Sanj2005 

Tnx for the feature request. Do you also have an idea where you want to show the info? Something like this?

![image](https://user-images.githubusercontent.com/11979740/32743163-ecf45f84-c8ab-11e7-9a58-2d61325daa5d.png)

**Comment by Sanj2005** [comment]
Many thanks for looking into this request
I think All this info should be on the top in bold with little larger font as this is title info

I have put some reference attached as below


![report](https://user-images.githubusercontent.com/31052167/32746037-815621dc-c882-11e7-8f28-0d30f5c49899.JPG)

See if we can put this on top as horizontally spread...

Also few more parameters will help like 
Execution environment : ste06,
executed by : 'zzxxxzz'

Thanks again !!!

**Comment by wswebcreation** [comment]
@Sanj2005 

Where is this report from?

**Comment by Sanj2005** [comment]
@wswebcreation 
This is Report from some other project which is developed in Java.
This is just a reference for you .....to clear the idea of headers data like - Application Name, Release, Cycle, Environment, executed by, start time & End time
Let me know if you need more info. Thanks!!!

**Comment by Sanj2005** [comment]
I have one more idea if you can allow us to pass BrowserStack build url to this Report.
these all will be great details to show on the Report.
Also you can keep all those parameters as optional and need to show usage examples in Read me.
What do you think ?

**Comment by Sanj2005** [comment]
Just to add more details here.....this BrowserStack url is basically BrowserStack session-id along with build-id for that perticualr execution, which users can generate in their framework & can pass to this Report using Options

**Comment by wswebcreation** [comment]
Hi @Sanj2005 ,

I think I can make this more generic like this:

```js
const report = require('multiple-cucumber-html-reporter');
report.generate({
      automaticallyGenerateReport: true,
      removeExistingJsonReportFile: true,
      removeOriginalJsonReportFile: true,
      openReportInBrowser: true,
      saveCollectedJSON: true,
      jsonOutputPath: './reports/report-plugin-json-output-folder/',
      reportPath: './reports/protractor-multiple-cucumber-html-report/',
      disableLog: false,
      metadataKey: 'deviceProperties',
      customData: [
            {
                  key: 'Project/Application Name',
                  value: 'XYZ Automation'
            },
            {
                  key: 'Release Name',
                  value: 'ABC'
            },
            {
                  key: 'Cycle',
                  value: '2'
            },
      ]
      customizedReportName : 'Multi Browser Protractor Cucumber HTML Report'
});
```

The array will be parsed and each key will be bold and the value will be normal like presented in the screenshot above. So you can provide a custom object will all the data you need. 

Would that provide in your needs?

**Comment by Sanj2005** [comment]
Hi @wswebcreation 
Yes.....I think this will help me.....I wanted to see how it looks like...Please let me know when you are pushing this..so that I can see how it looks..

Thanks again for looking into this!!!

**Comment by Sanj2005** [comment]
Hi @wswebcreation 
Kindly let me know if you updating this new enhancements & publishing a new Release version ?
Thanks!!!

**Comment by wswebcreation** [comment]
Hi @Sanj2005 

I've updated the report. Later this day / week I'll update https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin with the new data.
I hope it suites your needs. I'm going to close this for now.

**Comment by wswebcreation** [comment]
@Sanj2005 

I also release version 1.3.0 of https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin

**Comment by Sanj2005** [comment]
Yes I checked it....its looking gr8..Thanks!!!

**Comment by balajikrishnannewsuk** [comment]
Currently we are hard coding execution start time  and execution end time in custom data.How to get during run time?

**Comment by wswebcreation** [comment]
@balajikrishnannewsuk 

It depends on the framework and versions you are using. But during runtime you don't have access to the JSON object (the file is also not created yet), so you can't add it during runtime. You need to come up with sometime smart in your own framework to add this.

**Comment by balajikrishnan0815** [comment]
Hi Team,

In my framework,I have implemented to get execution start time from before hook and execution end time from after hook as show in below code.

var nodeDate = require('date-and-time');
var dateTime = nodeDate.format(new Date(), 'DD-MMM-YYYY, hh:mm:ss A');
before(()=>{
    cy.log('Global Before Hook');
    cy.log(dateTime); 
    
});

after(()=>{
    cy.log('Global After Hook');
    cy.log(dateTime);  
});

Please guide me how to get this value from before and after hook and map to Execution Start Time and Execution End Time.

**Comment by wswebcreation** [comment]
@balajikrishnannewsuk 

See my remark above, 

> It depends on the framework and versions you are using. But during runtime you don't have access to the JSON object (the file is also not created yet), so you can't add it during runtime. You need to come up with sometime smart in your own framework to add this.

I  don't know if you have access to it in Cypress, please ask the question there

**Comment by balajikrishnan0815** [comment]
Sure Wim,I will ask this question to Cypress forum.

**Comment by balajikrishnan0815** [comment]
How to get screenshots for each steps?,Can someone guide me how to implement with code.

**Comment by wswebcreation** [comment]
@balajikrishnannewsuk 

Again, that's framework depending, so not a question for here
