### ISSUE TITLE
TestCafe (steps not visible in html report)

### ISSUE THREAD

**Issue by umerhamdan10** [wswebcreation/multiple-cucumber-html-reporter#140]
My steps are not visible in report. I just see my feature file name and scenario name.

Any one face same issue? I just se json don't have any information about the steps but have the scenarion information.

Help will be appriciated 
![image](https://user-images.githubusercontent.com/43927146/110661734-2426e000-81c5-11eb-9eee-eb0afe7e00e5.png)

**Comment by umerhamdan10** [comment]
which file do you need? html ?

**Comment by umerhamdan10** [comment]
https://github.com/ash8454/testcafe-gherkin-demo

My situation is same as this project. After running all the feature file the report is generated well but not the steps.

if you run this project feature file you will see the issue. 

kindly let me know if you need more information.

Thanks for your time

**Comment by wswebcreation** [comment]
I need to have the JSON file. That file is being generated by TestCafe and should be a proper CucumberJSON object.

**Comment by umerhamdan10** [comment]
Here is the json file. Kindly let me know if you need more information.

Thanks for your help

**Comment by umerhamdan10** [comment]
This is **testcafe-reporter-cucumber-json.json**. Even I removed the tags but generating the same html report.

{
  "args": {
    "appName": false,
    "appVersion": false,
    "reportFolder": "cucumber-json-reports"
  },
  "noisyTags": [
    "(t)",
    "able",
    "and",
    "async",
    "but",
    "can",
    "cannot",
    "did",
    "feature",
    "fixture",
    "given",
    "not",
    "only",
    "scenario",
    "should",
    "spec",
    "test",
    "the",
    "then",
    "when",
    "with"
  ],
  "verbose": false
}

**Comment by wswebcreation** [comment]
Thanks for the info, I will take a look at it, just need to see when

**Comment by hdorgeval** [comment]
Hi @umerhamdan10, [https://github.com/ash8454/testcafe-gherkin-demo](https://github.com/ash8454/testcafe-gherkin-demo) enables you to write tests in a gherkin language, but behind the scene, these tests are executed by the `Testcafé` runner and not the `Cucumber` runner. 

In `Testcafé`, there is no notion of steps. 

See the disclaimer here : [Supported gherkin features and limitations](https://github.com/Arthy000/gherkin-testcafe#supported-gherkin-features-and-limitations)

This is why you will never see any step in the final html report.
I think you might be interested in this thread : https://github.com/hdorgeval/testcafe-reporter-cucumber-json/issues/29

Mixing Cucumber and Testcafé has always been a tedious task with a lot of trade-offs. You also might be interested by [testcafe-starter](https://github.com/hdorgeval/testcafe-starter)

**Comment by wswebcreation** [comment]
Thanks @hdorgeval 

Can you add a reference to your module in the readme? Would really appreciate it.

Closing the issue for now because it's a 3rd party dependency instead of an issue with this module

**Comment by hdorgeval** [comment]
Hi @wswebcreation, I just wondered which readme you are talking about?

The module referenced in this issue is [testcafe-reporter-cucumber-json](https://github.com/hdorgeval/testcafe-reporter-cucumber-json). It's a  JSON reporter for `TestCafé`, it produces a JSON document with the same format as the one generated by CucumberJS. I have created this reporter, so that TestCafé consumers can generate a nice HTML report through your module.
Thanks.

**Comment by wswebcreation** [comment]
Hi @hdorgeval 

Maybe promote your module in the readme in this project 😉
