### ISSUE TITLE
Filter Passed/Failed.. test in report 

### ISSUE THREAD

**Issue by elvisvan91** [wswebcreation/multiple-cucumber-html-reporter#141]
It will really good to have this feature. When running hundred of tests and there is some fail test. It will easy find fail tests quickly instead of scroll over the page to find them.
Thanks so much.

**Comment by wswebcreation** [comment]
Hi @elvisvan91 

Thanks for the idea. Do you also have an idea how you want to have this?

**Comment by elvisvan91** [comment]
Hi, thank for your reply.
When we go to the Feature page, there is a drop-down box filter only failed/passed/pending test, or check box to select failed/passed like pytest html report.
![image](https://user-images.githubusercontent.com/29598940/120828057-48a51500-c586-11eb-8218-4ffce89e5c84.png)

**Comment by wswebcreation** [comment]
Yes, you are correct, thanks for seeing this @BaCaRoZzo 

Closing this
