### ISSUE TITLE
Display tag names in report

### ISSUE THREAD

**Issue by gernotstarke** [wswebcreation/multiple-cucumber-html-reporter#142]
The tag names could be listed in the report, instead of just showing the symbol.

The symbol is the same for all tags

**Comment by wswebcreation** [comment]
Hi @gernotstarke 

I've added the icons (single for one tag and double for 2 or more tags) to keep it more clear. Tags can be used heavily/be very long and can mess up the table. 
There's a PR which will be released in a couple of days that will make it possible to filter on tags from the search box. I've you have any improvements on the design then please let me know. 

Going to close this one as this is how the report is currently working, but as said, if you have a better idea / design then please let me know
