### ISSUE TITLE
Background step is counted as separate Scenario in HTML report

### ISSUE THREAD

**Issue by kontownik** [wswebcreation/multiple-cucumber-html-reporter#143]
**Environment:**
 - multiple-cucumber-html-reporter:  v1.17.0
 - Node.js version: v15.6.0
 - NPM version: 7.6.2
 - Platform name and version: macOS 11.4
 - Cucumber version: cucumber-java:6.0.0

**Config of multiple-cucumber-html-reporter**
Default config

**Describe the bug**
After Background steps were added to the report here: https://github.com/wswebcreation/multiple-cucumber-html-reporter/commit/0dc03721b2f8e886acac1edc687b4af102fc8159
They are counted as separate Scenario, that leads to the situation where a single Scenario with Background steps included is counted as 2 Scenarios in the HTML report

**To Reproduce**
Try with this Scenario
```
Feature: Test

  Background:
    Given I accepted all the required app permissions

  @TEST
  Scenario Outline: Test
    Given I open the app
```

**Expected behavior**
Scenario count based on Scenarios and Scenario Outlines and NOT Background steps

**Additional context**
<img width="745" alt="Screenshot 2021-07-13 at 07 42 07" src="https://user-images.githubusercontent.com/3976951/125397876-d9091d80-e3ae-11eb-92f0-8bb68ec96649.png">

**Comment by wswebcreation** [comment]
thanks for the issue @kontownik 

I currently don't have a lot of time, so if there is anybody who wants to pick this up then it would be great

**Comment by kontownik** [comment]
Ok thanks for the info, I will take a look into it over the weekend. Not a Javascript expert but I think it's not so complicated, it counts incorrectly.

**Comment by kontownik** [comment]
Check results for Background Features tests

**Comment by kontownik** [comment]
@wswebcreation can I ask for code review?

**Comment by wswebcreation** [comment]
Closing this because the fix was released in August
