### ISSUE TITLE
Not able to see multiple-cucumber-html-reporter pie charts when running the cucumber tests on the CircleCI

### ISSUE THREAD

**Issue by Mandeepk01** [wswebcreation/multiple-cucumber-html-reporter#145]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: [e.g. 1.10.0]
 - Node.js version: [e.g. 8.9.1]
 - NPM version: [e.g. 5.8.0]
 - Platform name and version: [e.g. Windows 10]
 - Cucucmber version: [e.g. 4.2.0]

**Config of multiple-cucumber-html-reporter**
An example of how you configured the reporter in your config

**Describe the bug**
Not able to see multiple-cucumber-html-reporter pie charts when running the cucumber tests on the CircleCI

**To Reproduce**
Integrate your test suite with circleCI

**Expected behavior**

Local report is working fine and giving pie charts but when running the same code on Circle CI pie charts are missing
It should work as it is working in local

**Comment by wswebcreation** [comment]
Hi @MandeepKaur2020 

Sorry for my late response, I was on vacation. Thanks for submitting a bug, can you also provide your config for generating the report?
Did you also took a look at this https://github.com/wswebcreation/multiple-cucumber-html-reporter#usecdn?

**Comment by MandeepKaur2020** [comment]
Basically what happens is that when multiple-cucumber-html-reporter is integrated, it is working well in local but when I run through circle CI. It doesn't show the pie charts as attached.
<img width="1680" alt="Screenshot 2021-09-01 at 8 05 53 PM" src="https://user-images.githubusercontent.com/54873896/131691202-6714c276-b826-485e-aa70-2b7b4f045870.png">

**Comment by wswebcreation** [comment]
The charts might not be shown due to no access to the assets, can you check the devtools for errors in the console ?

**Comment by wswebcreation** [comment]
@Mandeepk01 

Any update on this?

**Comment by nabsofken** [comment]
@wswebcreation I am facing the same issue. There are console errors. I am on the latest version 1.18.3
<img width="1434" alt="Screen Shot 2021-12-01 at 6 58 52 PM" src="https://user-images.githubusercontent.com/1247761/144333350-66afc3eb-d3c7-47c5-8d78-7aed56f45bf5.png">
rs

**Comment by wswebcreation** [comment]
@nabsofken 

Can you provide your config here?

**Comment by nabsofken** [comment]
```onComplete: () => {
        // Generate the report when it all tests are done
        generate({
            // Required
            // This part needs to be the same path where you store the JSON files
            // default = '.tmp/json/'
            jsonDir: '.tmp/json/',
            reportPath: '.tmp/report/',
            pageTitle: 'Regression Report',
            reportName: 'Regression Report',
            // 4 more opts see https://github.com/wswebcreation/multiple-cucumber-html-reporter#options
        })
    },

**Comment by nabsofken** [comment]
@wswebcreation any updates on this?

**Comment by nabsofken** [comment]
@wswebcreation got some detailed logs and looks like the assets folder doesn't exist
```
ERROR @wdio/cli:utils: Error in onCompleteHook: Error: ENOENT: no such file or directory, stat '/Users/xxx/Desktop/cui-e2e-automation/node_modules/multiple-cucumber-html-reporter/templates/assets'
    at Object.statSync (node:fs:1536:3)
    at Object.statSync (/Users/xxx/Desktop/cui-e2e-automation/node_modules/graceful-fs/polyfills.js:311:34)
    at getStatsSync (/Users/xxx/Desktop/cui-e2e-automation/node_modules/multiple-cucumber-html-reporter/node_modules/fs-extra/lib/util/stat.js:58:18)
    at Object.checkPathsSync (/Users/xxx/Desktop/cui-e2e-automation/node_modules/multiple-cucumber-html-reporter/node_modules/fs-extra/lib/util/stat.js:90:33)
    at Object.copySync (/Users/xxx/Desktop/cui-e2e-automation/node_modules/multiple-cucumber-html-reporter/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at /Users/xxx/Desktop/cui-e2e-automation/node_modules/multiple-cucumber-html-report
er/lib/generate-report.js:554:8
    at Array.forEach (<anonymous>)
    at _createFeatureIndexPages (/Users/xxx/Desktop/cui-e2e-automation/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:520:18)
    at generateReport (/Users/xxx/Desktop/cui-e2e-automation/node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:143:2)
```
<img width="345" alt="Screen Shot 2021-12-16 at 11 22 29 PM" src="https://user-images.githubusercontent.com/1247761/146488568-e4597b2c-b27a-4b8c-87a7-924b4effbaf9.png">

**Comment by wswebcreation** [comment]
Hi @nabsofken 

Hmm, strange, this works on my machine , see 
![image](https://user-images.githubusercontent.com/11979740/149669549-bd27a842-947e-48ce-b4e7-859371f58fb0.png)


Which version are you using?
