### ISSUE TITLE
Reporter stops at feature number 10 and does not generate the rest of the HTML

### ISSUE THREAD

**Issue by johnson-tyl** [wswebcreation/multiple-cucumber-html-reporter#153]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.18.0
 - Node.js version: 12.18.3
 - NPM version: 6.14.11
 - Platform name and version: Windows 10
 - Cucucmber version: 7.2.1

**Config of multiple-cucumber-html-reporter**
`wdio.conf.js`:
```
reporter: [
['cucumberjs-json', {
        jsonFolder: './report/json',
        language: 'en',
    }]],

onComplete: function (exitCode, config, capabilities, results) {
        log.info('Generating Test report!');
        generate({
            pageTitle: 'E2E Test report',
            reportName: 'E2E Test report',
            displayDuration: true,
            jsonDir: './report/json',
            reportPath: `./report/multi-cukes-html/${moment().currentDate}/${moment().currentTime}`,
        });
        log.info('Finished generating Test report!');
    },
```

**Describe the bug**
The test spans 27 files and there 27 JSON files but cucumber-html-reporter stops at 10 every time we have run it. Not sure what's going on.

**To Reproduce**
1. Have more than 10 feature files in the run
2. Once the tests finish, open the html report generated by this plugin
3. Click on the 11th feature file on the Summary page, it will generate a 404 error.

**Expected behavior**
All HTML files should work as expected.

**Comment by johnson-tyl** [comment]
@wswebcreation thanks for your prompt reply.

Here's a few screenshots of the report and Windows Explorer showing the feature folder:

### Report Summary page:
![image](https://user-images.githubusercontent.com/63800148/136558574-41a4d6de-9c9c-426b-ac52-471448994708.png)

### Error Page:
![image](https://user-images.githubusercontent.com/63800148/136558620-e932d989-5eb4-4cc1-8750-cc816d5fcf2d.png)

### Expand the feature file in summary page:
![image](https://user-images.githubusercontent.com/63800148/136558699-0a5ce03f-bbaf-4575-9133-437daedfc08d.png)

### Files in the feature folder of report folder:
![image](https://user-images.githubusercontent.com/63800148/136558796-4e51325a-aedd-4932-82ec-66642dde53fd.png)

As you can see it stops generating after 10 files, however there's 27 feature files in total. I am also using `wdio-cucumberjs-json-reporter` to generate the json report and I know the JSON files are fine otherwise the summary wont be visible.

**Comment by johnson-tyl** [comment]
Sorry, this is not happening because of the number of files but name of the feature. The name of the feature is way too long for it to handle. I am closing this defect.

**Comment by wswebcreation** [comment]
@johnson-tyl 

Can you provide some more info as requested, otherwise I might need to close this issue
