### ISSUE TITLE
Some screenshots (attachments) are not loading in the html report 

### ISSUE THREAD

**Issue by clraghuram** [wswebcreation/multiple-cucumber-html-reporter#159]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: [e.g. 1.18.0]
 - Node.js version: [e.g. 14.16.1]
 - NPM version: [e.g. 6.14.2]
 - Platform name and version: [e.g. macOS Big Sur]
 - Cucucmber version: [e.g. 7.2.1]

**Config of multiple-cucumber-html-reporter**
An example of how you configured the reporter in your config

**Describe the bug**
1. Unable to open the screenshot link in the HTML Report

**To Reproduce**
1. Create a json with 11 scenarios and 14 steps in each scenario, all steps having the embedded screenshot data
2. Generate the report with Browser.
3. Launch the HTML report, and try to open the screenshot for 11th scenario and 3rd step.
4. The screenshot doesn't load.
[Include code or an example repository that can easily be set up]

**Expected behavior**
1. The screenshot should load for all the feature steps.
**Log**
If applicable, add logs to help explain your problem. If you don't have log, enable 'debug:true' in the config and paste the log here.
Please use proper markdown to style it

**Additional context**

This can be fixed if the scenarioIndex and stepIndex are separated by a character in scenarios.tmpl file.
![image](https://user-images.githubusercontent.com/24761344/143900177-75dbf079-229c-4421-877b-04a0ffda13ef.png)

**Comment by clraghuram** [comment]
Can I raise a PR for this fix?

**Comment by wswebcreation** [comment]
Thanks for raising this issue, closing this because https://github.com/wswebcreation/multiple-cucumber-html-reporter/pull/160 will solve this

**Comment by wswebcreation** [comment]
Released a new version, see https://github.com/wswebcreation/multiple-cucumber-html-reporter/releases/tag/v1.18.3
