### ISSUE TITLE
Documentation out of date for cucumber-js v3

### ISSUE THREAD

**Issue by LennDG** [wswebcreation/multiple-cucumber-html-reporter#16]
For cucumber-js v3 the `AfterFeatures` hook does not exist anymore and the reporter should be run in a separate process as indicated in this issue:
https://github.com/cucumber/cucumber-js/issues/918

**Comment by wswebcreation** [comment]
Hi @LennDG 

Tnx, you are right, can you add that in a PR?

**Comment by LennDG** [comment]
Small PR sent.

**Comment by wswebcreation** [comment]
Fixed with https://github.com/wswebcreation/multiple-cucumber-html-reporter/pull/17

Tnx!
