### ISSUE TITLE
Hi WsWebCreation!... I was wondering if you could help ...

### ISSUE THREAD

**Issue by Niemetz** [wswebcreation/multiple-cucumber-html-reporter#163]
to create a cucumber report for the Playwright test automation framework?  Or would you provide instructions on how to run /generate a report from a set of cucumber json files?
  Thanks!
  J.N

**Comment by wswebcreation** [comment]
Hi @Niemetz 

Thanks for the issue, but sorry, I don't have an example for this. I hope someone else can help with this

**Comment by Niemetz** [comment]
Hi Wim
  I was able to figure it out.  Thanks a lot for responding to my inquiry though!
  J.N

**Comment by wswebcreation** [comment]
YW,

If you've figured it out, would you mind sharing that info and raise a PR?

**Comment by mothuc** [comment]
@Niemetz Can you share the solution for that?
