### ISSUE TITLE
Ability to override custom metadata per report not working in v1.19

### ISSUE THREAD

**Issue by ssteezens** [wswebcreation/multiple-cucumber-html-reporter#169]
UPDATE 3/24/22:  

I think this is actually a bug in v1.19.  When using v1.18.0 the below works as expected, where the metadata specified in `report.generate` acts as the "default" metadata and is only used when there is not metadata specified within the individual report json.

This issue can also be found in this [link](https://wswebcreation.github.io/multiple-cucumber-html-reporter/custom-metadata/index.html) on the readme 

=============================

Hello, I originally posed this question on the gitter, but i'm putting it here for better tracking.  

I noticed that metadata within a report's json overrides the default meta specified when generating a report.  I was wondering if this was also possible with custom metadata?

i.e if I generate the report with a custom 'app' and 'type' metadata properties
```
report.generate({
         jsonDir: cucumberJsonDir,
         reportPath: htmlReportDir,
         displayDuration: true,
         useCDN: true,
         pageTitle: 'Hello World E2E',
         reportName: `Hello World E2E - ${new Date().toLocaleString()}`,
         customMetadata: true,
         metadata: [
            {name: 'app', value: 'Hello World'},
            {name: 'type', value: 'Test type v1'},
         ],
         ...
      });
```
would it be possible to overrides these default values in the report's json like so
```
[
  {
    "keyword": "Feature",
    "name": "Hello-Integration",
    "line": 1,
    "id": "hello-integration",
    "tags": [],
    "uri": "hello-integration.feature",
    "metadata": {
      "app" : "Hello world",
      "type": "Test type v2"
   },
    "elements": [
     ...
```

**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter:  1.19.0
 - Node.js version: 14.18.1
 - NPM version: 8.1.1
 - Platform name and version: MacOS Monterey 12.0.1
 - Cucucmber version: 5.1.0

**Additional context**
in my circumstance I need a way to add an additional column (outside of the default metadata properties) to the report table with a variable that can change for an individual row.

**Comment by wswebcreation** [comment]
This is fixed with [this](https://github.com/wswebcreation/multiple-cucumber-html-reporter/releases/tag/v1.20.0) release, can you check that and if so close this issue?

**Comment by ssteezens** [comment]
Awesome, looks like it works now, thanks a lot!
