### ISSUE TITLE
CustomMetadata from the features is ignored in 1.19.0

### ISSUE THREAD

**Issue by BaCaRoZzo** [wswebcreation/multiple-cucumber-html-reporter#170]
In our use case we execute tests on separated embedded devices, adding custom Metadata at the json file level.
The json files are then stashed in our pipeline to be gathered for report generation. 

Up until version `1.18.3` this worked flawlessly with the feature overview being populated with the custom metadata. On version `1.19.0` the feature overview does not include _any_ of the custom metadata we insert in the json files.

Documentation-wise for `metadata` it is mentioned that the data from the features takes precedence over the passed metadata. I think that should be the same for `customMetadata`. However, [this commit](https://github.com/wswebcreation/multiple-cucumber-html-reporter/commit/23da010d0170f3bdfe12314eeb630d8cb2678a75) introduced in version `1.19.0` does not execute any kind of check over the `feature.metadata`. Instead it assigns `options.metadata` directly.

**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.19.0
 - Node.js version: 12.22.7
 - Yarl version: 1.22.15
 - Platform name and version: Linux (amx64/armhf)
 - Cucumber version: 6.0.5

**Expected behavior**
The metadata from the feature should take precedence over the metadata passed as parameter. As mentioned the metadata _value_ can vary a lot in some cases like ours and it doesn't make sense to set an _overall_ custom metadata at all but instead rely on the metadata already available in the files.

**Comment by wswebcreation** [comment]
I've released a new version, thanks for your contribution
