### ISSUE TITLE
Charts bug after Chromium version 100 (Browsers chrome, edge, etc)

### ISSUE THREAD

**Issue by kwelf** [wswebcreation/multiple-cucumber-html-reporter#172]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.19.0
 - Node.js version: 16.14.0
 - NPM version: 8.5.5
 - Platform name and version: Windows 10
 - Cucucmber version: "@wdio/cucumber-framework": "^7.19.0"

**Describe the bug**
Charts bug after Chromium version 100 (Browsers chrome, edge, etc).
In Firefox works fine.

**To Reproduce**
Just make a report and open in Chrome version = 100

**Bug Behavior**
![image](https://user-images.githubusercontent.com/42254845/161997396-fab352cc-d82b-4c2b-b031-7668874bf404.png)

**Comment by wswebcreation** [comment]
Hi @kwelf 

I've checked it on my machine

<img width="440" alt="image" src="https://user-images.githubusercontent.com/11979740/162125344-9bdcf2ab-6daa-445d-99bb-5d0bd6980c10.png">

And I'm not seeing any issues

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/11979740/162125376-917bdabe-1a72-4dd6-a90e-4b451da87e72.png">

See this page https://wswebcreation.github.io/multiple-cucumber-html-reporter/browsers/index.html

Do you have an example somewhere?

**Comment by wswebcreation** [comment]
I also don't see this on Windows 10 with Chrome 100

<img width="907" alt="image" src="https://user-images.githubusercontent.com/11979740/162125574-a58c594f-48ae-4c12-a04c-e4e6cadc8814.png">

**Comment by kwelf** [comment]
Ok guys, if it's only me I will close this and try to investigate my project.
Thanks a lot all
