### ISSUE TITLE
Donut charts do not pick color customization

### ISSUE THREAD

**Issue by BaCaRoZzo** [wswebcreation/multiple-cucumber-html-reporter#176]
**Is your feature request related to a problem? Please describe.**
Last week I was playing around with the `css` customization to try some company-theming. It worked well but I noticed that the donut charts are not affected. I've digged a bit into the code and found out that the colors are hard-coded, see e.g. [here](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/main/templates/features-overview.index.tmpl#L159-L166).
I've digged into the `css` and, given that I'm not an expert in the subject, it seems to me not possible to customize such colors at the moment.

**Describe the solution you'd like**
Ideally, some way to customize charts colors. Possibly via some `css` property of sort.

**Describe alternatives you've considered**
I've toyed around with [`custom properties`](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties). They are [largely supported](https://www.lambdatest.com/web-technologies/css-variables) and, I think, they could be a good fit. AFAICT they are also [endorsed upstream](https://github.com/chartjs/Chart.js/issues/9983).

**Comment by BaCaRoZzo** [comment]
@wswebcreation assuming I read the code correctly, do you have any idea how to implement the customizations? Would be using custom properties a viable solution for you? I would attempt to provide a PR, if so.
I'd really love to have the donut themed much like the rest of the report. :smile:

**Comment by wswebcreation** [comment]
Hi @BaCaRoZzo 

Thanks for this Feature Request. It is a possibility to do this with custom properties. I only want to revamp the module for this year, meaning moving off Lodash Templates, jQuery, dataTables and come up with a new design (only time is not my biggest friend at the moment).
For now I'm fine with a PR on the donuts but feel free to also change some other stuff

**Comment by BaCaRoZzo** [comment]
@wswebcreation the roadmap sounds nice, thanks for the hard-work you put in maintaining such a nice project!
I'll prepare the PR then.

>For now I'm fine with a PR on the donuts but feel free to also change some other stuff

Probably some minor fixes but don't think I'm going for nothing more. I'm honestly a bit out of my expertise scope here. :sweat_smile:

**Comment by wswebcreation** [comment]
Closing this one thanks to your PR, we will proceed the the conversation there
