### ISSUE TITLE
Allow to have custom descriptions

### ISSUE THREAD

**Issue by BaCaRoZzo** [wswebcreation/multiple-cucumber-html-reporter#179]
**Is your feature request related to a problem? Please describe.**
In #165 - see https://github.com/wswebcreation/multiple-cucumber-html-reporter/pull/165/files#diff-f636bfb0df22d3bbf3cafd055aade8504a71e6484475ae0f60d09b2c9552fe07L76 - the feature description was augmented to a more pleasant structure with the addition of a bold `description` text at the beginning and the addition of some other fields. 

Unfortunately we are not really interested in those fields. Furthermore, we want  to specifically format descriptions in our custom way which would not fit in the current format.

**Describe the solution you'd like**
Initially we thought about introducing the aforementioned custom formatting directly here. But  that would be too specific. A good middle-ground would be to allow for copying the descriptions verbatim, hence offloading the formatting to the caller. So basically we revert to the code before #165 if the flag is used, also dropping the newly added fields.

**Comment by wswebcreation** [comment]
Closing this one due to the PR you've created, thanks for that!
