### ISSUE TITLE
Allowing custom metadata

### ISSUE THREAD

**Issue by LennDG** [wswebcreation/multiple-cucumber-html-reporter#18]
The code that Cucumber tests in my project does not have anything to do with browsers, devices or OS. It does however have other environment variables that change between different features.

It would be nice if there was a way to define custom metadata instead of the static metadata currently present.

I am willing to create a PR that updates the project to allow for this if this is not already a feature of the project that I somehow missed.

**Comment by wswebcreation** [comment]
Hi @LennDG 

If I understand you correctly you want something like [this](https://github.com/wswebcreation/multiple-cucumber-html-reporter#customdata) also for each feature-file?

**Comment by LennDG** [comment]
Sort of. I would like to be able to change the names of the 3rd through 7th column of [the example] (https://wswebcreation.github.io/multiple-cucumber-html-reporter/), add extra columns if necessary and pass their values as with the metadata system now.

As I see it you would be able to put a metadata field at the instantiation of multiple-cucumber-html-reporter like:
```
metadata:{
    test_environment: {
        value: 'my_env'
    },
    environment_ip: {
        value: '1.2.3.4'    
    }
}
```

And it would show two columns with the values for these fields for each feature, as it is now with browsers and devices.

For my purposes there is no need for multiple fields per column as with the browser/browser version in the current metadata.

**Comment by wswebcreation** [comment]
Hmm,

Sounds interesting. I'm interested in how you would do that so please provide an example / PR

**Comment by LennDG** [comment]
I will update once I have drilled down into the code to find what needs to be changed.

**Comment by LennDG** [comment]
I have created a [pull request](https://github.com/wswebcreation/multiple-cucumber-html-reporter/pull/19) with the proposed addition.

**Comment by wswebcreation** [comment]
Hi @LennDG 

I saw it, but I don't have time to look at it today, hope to have time for it this weekend

**Comment by wswebcreation** [comment]
Added it with this PR https://github.com/wswebcreation/multiple-cucumber-html-reporter/pull/19

Going to close it now. Tnx for helping with this nice feature
