### ISSUE TITLE
Adding custom data with wdio

### ISSUE THREAD

**Issue by sajjadh** [wswebcreation/multiple-cucumber-html-reporter#191]
I am wondering how should i add the custom data in wdio config file.  the below code didnt work

![image](https://user-images.githubusercontent.com/31664351/172338389-77c8534a-bbc8-4dda-b43c-a0cf727d2a1c.png)

**Comment by wswebcreation** [comment]
Hi @sajjadh 

This report is not related to WebdriverIO, feel free to create an issue [here](https://github.com/webdriverio-community/wdio-cucumberjs-json-reporter/issues) and provide all needed information to reproduce this
