### ISSUE TITLE
getChartColors is not defined

### ISSUE THREAD

**Issue by Yangfan2016** [wswebcreation/multiple-cucumber-html-reporter#192]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: [1.21.2]
 - Node.js version: [14.17.4]
 - NPM version: [6.14.14]
 - Platform name and version: [Macos 11.4]
 - Cucucmber version:  cypress-cucumber-preprocessor [4.2.0 ]

**Config of multiple-cucumber-html-reporter**
An example of how you configured the reporter in your config

**Describe the bug**

<img width="574" alt="image" src="https://user-images.githubusercontent.com/17830872/173180128-800b3abe-79e2-4a6b-9486-962706571cff.png">
<img width="766" alt="image" src="https://user-images.githubusercontent.com/17830872/173180216-c4f332f0-2a37-4d76-a689-16df7660762c.png">

**To Reproduce**

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem. If you don't have log, enable 'debug:true' in the config and paste the log here.
Please use proper markdown to style it

**Additional context**

**Comment by wswebcreation** [comment]
@Yangfan2016 

Can you please provide your config or more information, this is not really helpful. I've ran it on my machine and I don't have any errors

**Comment by morochena** [comment]
I just started receiving the same error today - this is my config if it's helpful:

```
cucumberReporter.generate({
    jsonDir: "/tmp/cucumber",
    reportPath: "/tmp/cucumber/reports",
    pageTitle: "Cucumber Report",
    reportName: "Cucumber Report",
    useCDN: true,
    displayDuration: true,
    hideMetadata: true,
    customData: {
      title: "Info",
      hideMetadata: true,
      data: [
        { label: "Project", value: "Formability" },
        { label: "Generated At", value: `${new Date().toDateString()} ${new Date().toTimeString()}` },
        { label: "Git Commit", value: `<a href=${commitUrl} target="_blank">${commitId}</a>` },
        { label: "Test Failures", value: `<a href="failures.txt" target="_blank">Link</a>` },
        { label: "Test Flakies", value: `<a href="flakies.txt" target="_blank">Link</a>` },
      ],
    },
  });
  ```

**Comment by wswebcreation** [comment]
Sorry, I haven't been able to reproduce it so I can fix it, any help here would be appreciated

**Comment by morochena** [comment]
@wswebcreation the issue occurs if you are using the `useCDN` option and are only expecting to serve the generated report html without any extra dependencies. Serving `templates/assets/js/Chart.style.js` through a CDN when the option is selected would be one option.
