### ISSUE TITLE
"PASSED" step.result.status within JSON is being interpreted as Skipped by the report generation

### ISSUE THREAD

**Issue by michaelsc93** [wswebcreation/multiple-cucumber-html-reporter#199]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.21.4

**Config of multiple-cucumber-html-reporter**
Default configuration, freshly installed.

**Describe the bug**
Using Cypress with Cucumber, the JSON output after formatting from .ndjson into .json has steps.result.status value in capitals. This leads the multiple-cucumber-html-reporter to present them as Skipped due to case sensitivity.

EG:
```
"steps":[{"keyword":"Given ","line":8,"name":"the region and audience selection form is opened","result":{"status":"PASSED"
```
appears as Skipped.

The fix would be quite simple, within _parseSteps function the status can be changed toLowerCase() to work for any context.

Line 377 onwards:
```
			if (step.result.duration) {
				scenario.duration += step.result.duration;
				step.time = formatDuration(step.result.duration)
			}

			if (step.result.status.toLowerCase() === RESULT_STATUS.passed) {
				return scenario.passed++;
			}

			if (step.result.status.toLowerCase() === RESULT_STATUS.failed) {
				return scenario.failed++;
			}

			if (step.result.status.toLowerCase() === RESULT_STATUS.notDefined) {
				return scenario.notDefined++;
			}

			if (step.result.status.toLowerCase() === RESULT_STATUS.pending) {
				return scenario.pending++;
			}

			if (step.result.status.toLowerCase() === RESULT_STATUS.ambiguous) {
				return scenario.ambiguous++;
			}

			scenario.skipped++;
```

Please let me know if this is a good solution & if it could be added. 
I have done it locally to have our reports appearing correctly but it would be great to have it in case of future versions :)

**Comment by michaelsc93** [comment]
Actually there are more reporting issues under the FAILED condition than the one I have fixed, the capitals in the JSON must be impacting other areas of the report.

**Comment by wswebcreation** [comment]
Closing this one as it will be fixed by this PR https://github.com/wswebcreation/multiple-cucumber-html-reporter/pull/207
