### ISSUE TITLE
Show table in steps

### ISSUE THREAD

**Issue by brbernardo90** [wswebcreation/multiple-cucumber-html-reporter#2]
The report don't show the table of each step.

Image with the step: 

![report_issue3](https://user-images.githubusercontent.com/15858324/28035878-917564e6-658c-11e7-8ade-a0df9b3ed397.png)

Image with the report without the table:

![report_issue2](https://user-images.githubusercontent.com/15858324/28035892-a311370c-658c-11e7-9490-60f3ec897bc7.png)

**Comment by wswebcreation** [comment]
Hi,

Can you please provide all the info as mentioned in your first issue so I can see what the problem is?

In my current project:

**The json for the table**
![image](https://user-images.githubusercontent.com/11979740/28038041-d647cad8-65bd-11e7-8423-74fba92541fd.png)

**The output**
![image](https://user-images.githubusercontent.com/11979740/28038079-f18d6b9a-65bd-11e7-870f-e3fe5e94029a.png)

**Comment by brbernardo90** [comment]
@wswebcreation 

My json is different, I'm using cucumber (2.4.0 for Ruby) and your project is for CucumberJS, I'm so sorry for open the issues but is almost working 100%.

This is the json:
![report_issue6](https://user-images.githubusercontent.com/15858324/28071494-7c867526-6626-11e7-989b-03f4d2f4dc7e.png)

**Comment by brbernardo90** [comment]
This is my complete json (I change the extension to can upload):

[report.txt](https://github.com/wswebcreation/multiple-cucumber-html-reporter/files/1139100/report.txt)

**Comment by wswebcreation** [comment]
Hi,

I think the problem is [here](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/master/templates/components/scenarios.tmpl#L168). The template expects that the `rows` are part of `step.argurments` and you don't have `step.argurments`

It looks like the json that is generated by Cucumber for Ruby is not giving the same json structure. Can you find that in the documentation of Cucumber for Ruby? If I know what the differences are I can maybe create a feature for it so my report also supports Cucumber for Ruby

**Comment by brbernardo90** [comment]
Hi,

i can't find in the doc http://www.rubydoc.info/github/cucumber/cucumber-ruby/

Is not possible change just with the json example?

**Comment by wswebcreation** [comment]
Hi,

If I'm going to implement it, I want it to be good ;-). That means that I need to have as much info as I can get to adjust the templates. What would be nice if you can provide json files for the following situations (see also https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/master/test/unit/data/json/:

- ambiguous scenarios (scenario's have been scripted twice)
- failed scenario's (Failed scenario's should have attached screenshots and stacktrace)
- happy flow (with for example an inline datatable)
- pending scenario's
- skipped scenario's
- undefined scenario's

If you can provide that I can look into them and create a new release in the coming weeks (kinda busy lately)

**Comment by brbernardo90** [comment]
Great! I'm going to do It!

Thank's

**Comment by brbernardo90** [comment]
This is the scenarios, I can't reproduce ambiguous cause ruby crash:

![report_issue7](https://user-images.githubusercontent.com/15858324/28181033-8819310e-67dd-11e7-86f7-cf54ad34453f.png)

And this is the json:

[report.txt](https://github.com/wswebcreation/multiple-cucumber-html-reporter/files/1146180/report.txt)

**Comment by wswebcreation** [comment]
Tnx, will take a look at it, will let you know

**Comment by wswebcreation** [comment]
@brbernardo90 

Doesn't look like you added the full json of the above scenario's, it only holds the first. CAn you provide a new json?

**Comment by brbernardo90** [comment]
Good Morning!

Answering the other issue, yeah, the problem persist with Google Chrome but works with Safari (titles of scenarios), look:

![report_issue8](https://user-images.githubusercontent.com/15858324/28318825-8435bb5c-6ba2-11e7-9cd7-40c220f0192d.png)

This is the json that I used to do the image.

[report.txt](https://github.com/wswebcreation/multiple-cucumber-html-reporter/files/1155953/report.txt)

**Comment by wswebcreation** [comment]
Can you make your screen bigger, there's a css breakpoint in the code to not show the titel

**Comment by brbernardo90** [comment]
man, I don't understand, screen bigger? is there a breakpoint?

![-users-brbernardo-documents-saber-testes_automatizados-saber-bdd-report_html-features-c7e77ba4-da84-40c3-9f28-8fac69a8197c-test html](https://user-images.githubusercontent.com/15858324/28322144-be9d29ac-6bab-11e7-99e7-06e9fc2b3f5d.png)

**Comment by wswebcreation** [comment]
Yeak, a css breakpoint on the with of your screen. If it is smaller then 1270px you will not see the Scenario name

![image](https://user-images.githubusercontent.com/11979740/28329519-66522056-6bea-11e7-9396-f5eb9e54186b.png)

**Comment by wswebcreation** [comment]
Going to close this due to inactivity
