### ISSUE TITLE
Show feature as skipped if all scenarios in it are skipped

### ISSUE THREAD

**Issue by kevinkuszyk** [wswebcreation/multiple-cucumber-html-reporter#20]
I think it would be useful to show a feature as skipped if all it's scenarios are skipped.  

For example, instead of this:

![image](https://user-images.githubusercontent.com/2734580/34048433-91fd435c-e1ab-11e7-840e-653872f963d0.png)

Show the skipped icon instead:

![image](https://user-images.githubusercontent.com/2734580/34048480-c4828080-e1ab-11e7-92c3-98c5aea7147b.png)

If you can give me a steer on what needs changing, I'll send a PR.

Thanks!

**Comment by wswebcreation** [comment]
Hi @kevi kuszyk

You are right, but so need to check the CucumberJS output in detail. As far as I can remember the endstatus of the feature is successful and they don't know a pending status on the complete feature. Will come back on that.

**Comment by kevinkuszyk** [comment]
Thanks - when I looked at our `cucumber_report.json` files the status was either passed or failed.  I'll take another look today.

**Comment by wswebcreation** [comment]
Fixed with version 1.4.1
