### ISSUE TITLE
Data Table within cucumber step not displaying in the report

### ISSUE THREAD

**Issue by Krishnan-OP** [wswebcreation/multiple-cucumber-html-reporter#201]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: [e.g. 1.10.0] - 1.21.4
 - Node.js version: [e.g. 8.9.1] - 10.19.0
 - NPM version: [e.g. 5.8.0] - 6.14.4
 - Platform name and version: [e.g. Windows 10] - Windows 10
 - Cucucmber version: [e.g. 4.2.0] - 5.7.0

**Config of multiple-cucumber-html-reporter**
From within Jenkins pipeline setting up the report in a stage block:
```
    sh("sudo apt install npm -y")
    sh("sudo npm install -g n")
    sh("sudo n 14.9.0")
    sh("sudo npm i multiple-cucumber-html-reporter@1.21.4")
    sh("sudo node ./index.js")
    sh("sudo cp -R -f -u node_modules/multiple-cucumber-html-reporter/templates/assets/ ./")
    sh("sudo cp -R -f -u node_modules/multiple-cucumber-html-reporter/templates/components/ ./")
```
last two copy I had to copy over all the assets to be able to get dark mode working.
 
**Describe the bug**
In feature file I have:
```
  Scenario: Check Dependency Top Level nodes
    Given 'jCapeserver' should be running on 'Ubuntu'
    When we execute 'Dependency-Demo-Data-Top-Level' API test on 'Ubuntu'
        |SCENARIO|DEFINITION_ID|NAME|EXPECTED_STATUS|
        |Top Level Dependency|d42013e7-a1bd-4d9a-aa8b-c77bd65e60a9|Thingsboard|200|
    Then 'Dependency' should pass all API tests on 'Ubuntu'
```
I was expecting to see in the reports:
![image](https://user-images.githubusercontent.com/88673377/179742942-c40f5f3b-a926-445a-9e65-15e64152e103.png)
But in the report generated it neither shows the data table

**To Reproduce**
1. Create a feature file with data table in a step
2. Execute the automation script to generate the result json
3. Compile the report based on the result json

[Include code or an example repository that can easily be set up]

**Expected behavior**
I want to see the data table when I expand the step (in any results status like Pass, Fail etc) to be able to see the data table.
![image](https://user-images.githubusercontent.com/88673377/179743306-7111c4dc-70c0-4474-bcd1-647429d95b9d.png)

**Log**
N/A

**Additional context**
It will help in providing clarity to the consumers of the report to know the test data against which the step has been executed.

**Comment by wswebcreation** [comment]
Hi @Krishnan-OP 

Can you provide the JSON output?

I've also checked the report that you're showing here, and it doesn't look like this report. Did you alter a lot?

When I run this feature

```feature
Feature: Output with scenario outline and data tables

  Background: When I do nothing
    Given This is doing nothing because it's a background

  Scenario: inline table example
    Given I am a inline table step
      | name | last |
      | John | Doe  |

  Scenario Outline: Google outline inline table <time>
    Given I am a inline table step with examples for the <time> time
      | time   | weather    |
      | <time> | <wheather> |

    Examples:
      | time   | wheather |
      | first  | cold     |
      | second | warm     |

```

I get this output
![image](https://user-images.githubusercontent.com/11979740/182312540-3fb81a95-bf7d-4763-b771-e399c2cdde36.png)

So I'm not sure what the issue is

**Comment by wswebcreation** [comment]
Closing this one due to inactivity
