### ISSUE TITLE
multiple-cucumber-html-reporter not working with badeball / cypress-cucumber-preprocessor

### ISSUE THREAD

**Issue by frnc07** [wswebcreation/multiple-cucumber-html-reporter#208]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.21.6
 - Node.js version: 14.15.3
 - NPM version: 8.14.0
 - Cucucmber version: @badeball/cypress-cucumber-preprocessor@12.0.0

**Config of multiple-cucumber-html-reporter**
**Package.json:**
```
"@badeball/cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "nonGlobalStepBaseDir": "cypress/e2e/**/*.{js,ts}",
    "stepDefinitions": "cypress/e2e/**/*.{js,ts}",
    "messages": {
      "enabled": true,
      "output": "cypress/cucumber/cucumber-messages.ndjson"
    },
    "json": {
      "enabled": true,
      "output": "cypress/cucumber/cucumber-report.json",
      "filePrefix": "cucumber-",
      "fileSuffix": ""
    }
  }
```

**report.js:**
```
const report = require('multiple-cucumber-html-reporter')

report.generate({
  jsonDir: 'cypress/cucumber/',
  reportPath: 'cypress/reports',
  metadata: {
    browser: {
      name: 'chrome',
      version: '90'
    },
    device: 'Local test machine',
    platform: {
      name: 'ubuntu',
      version: '16.04'
    }
  },
  customData: {
    title: 'Run info',
    data: [
      { label: 'Project', value: '' }
    ]
  },
  displayReportTime: true,
  hideMetadata: true,
  saveCollectedJSON: true,
  pageTitle: '',
  reportName: '',
  displayDuration: true
})
```

**Describe the bug**
Not able to create html report from the json files created after each test run

**Additional context**
This was working find earlier with older version 4.1.4 of cypress-cucumber-preprocessor

**Comment by volkanogretmen** [comment]
It wasn't working for me either, but you probably forgot to install this formatter:
https://github.com/cucumber/json-formatter

Follow the instructions for your specific OS. Reload VS Code and you should be good to go.

E.g. for Windows:

1. Download cucumber-json-formatter-windows-amd64 from https://github.com/cucumber/json-formatter/releases/tag/v19.0.0 and rename it to cucumber-json-formatter.exe
2. Move it to a directory that's on your PATH
-- Right click on Start Button > System. 
-- Click in right bar Advanced System Settings
-- Click the "Environment Variables" button on the first page
-- At the top section, click on the variable "Path"
-- Add a new line with a location of your choice (e.g. C:\Users\...)
-- Click OK and OK again
3. Restart VS Code (or your preferred editor)
4. Verify that you can run it: `cucumber-json-formatter --help`
-- It should return something like "Usage of..."
5. Make sure to have both json and massages output enabled in `.cypress-cucumber-preprocessorrc`
6. Run your Cypress tests
7. Alternatively, when you already have a json/message out, run `node cucumber-html-report.js`

**Comment by wswebcreation** [comment]
Thanks @volkanogretmen 

Do you want to add this as a PR to the docs?

@frnc07 
Closing this for now based on the solution that @volkanogretmen provided
