### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by LennDG** [wswebcreation/multiple-cucumber-html-reporter#21]
Just a heads up, the links that go to the samples of the [browser](https://wswebcreation.github.io/browsers) and [custom metadata](https://wswebcreation.github.io/custom-metadata/) in the introduction are dead.

Not sure how to fix that.

**Comment by wswebcreation** [comment]
Hi @LennDG 

Tnx for this issue. I made an error with the links and I've fixed it with [this commit](https://github.com/wswebcreation/multiple-cucumber-html-reporter/commit/c7aafe19a6f167b054e77505d46c2cfa4beeb566).

Tnx again!
