### ISSUE TITLE
Seeing different multiple cucumber html reporter when test fails

### ISSUE THREAD

**Issue by Kusams** [wswebcreation/multiple-cucumber-html-reporter#212]
Seeing different multiple cucumber html reporter when test fails.
When the test pass, report showing as expected in the git repo screenshots, however when the test fails report looks different.
Please find the attachments for reference.

**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.20.0
 - Node.js version: v14.17.4
 - NPM version: 8.7.0
 - Platform name and version: mac
 - Cucucmber version: 8.2.0
- project : cucumber BDD with javascript.
[htmlreport_fail.pdf](https://github.com/wswebcreation/multiple-cucumber-html-reporter/files/9535584/htmlreport_fail.pdf)
[htmlreport_pass.pdf](https://github.com/wswebcreation/multiple-cucumber-html-reporter/files/9535585/htmlreport_pass.pdf)

**Comment by wswebcreation** [comment]
This is not an issue. The report does not know the context of each file, it just reads the json files from the provided folder and creates a report out of it. If you don't want certain results in it then please remove those files before you kick of the process to create a report out of them
