### ISSUE TITLE
How to display HTML report in azure pipeline tab?

### ISSUE THREAD

**Issue by strymsg** [wswebcreation/multiple-cucumber-html-reporter#216]
Hi, I was trying to use some azure pipeline extensions to show the generated report in a tab, but I'm still unable to do it. I tested with: 
[HTML report viewer](https://marketplace.visualstudio.com/items?itemName=JakubRumpca.azure-pipelines-html-report), but each scenario has its own file so the viewer cannot follow the `<a href="...">` links, plus css and js are not being loaded.

![image](https://user-images.githubusercontent.com/35537786/192892779-d3eecc90-9ac8-45a9-97ee-ba16ac57621a.png)

Any ideas of how to properly display the `index.html` in a tab for azure pipelines?

**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 2.0.0
 - Node.js version: 16
 - NPM version: 8.11
 - Platform name and version: debian 11
 - Cucucmber version: 7.3.0

### A workaround I tried.

With external code, I merged all reports into a single HTML by looping through all `feature/*.html` files, getting the content of `div.main_container` and adding to the index.html file and looks good, HTML report viewer shows the complete report. I'm trying to follow the same approach with css and js files, but I'm still new with bundlers. 

I wonder if a feature to generate a single HTML file can be done :thinking:

**Comment by wswebcreation** [comment]
Hi @strymsg 

Regarding the js/css issue, the screenshot that you shared, is that the first page that is loaded? The assets are by default loaded from an assets folder, you can also use [`usecdn: true`](https://github.com/wswebcreation/multiple-cucumber-html-reporter#usecdn) in your config and then it will be loaded from a CDN

I don't know how the Azure plugin works, but my suggestion would be to check with the plugin. This module loads the data in a new url

**Comment by strymsg** [comment]
Hi @wswebcreation , the screenshot is how the plugin shows the generated `index.html` file. useCDN looks good it did the trick with the css/js resources.

![image](https://user-images.githubusercontent.com/35537786/194641608-fe9824a9-983c-4bdc-b7af-e7f6aafe7b01.png)

Regarding the feature/*.html files I used the workaround mentionend before and it is all properly displayed in the pipeline. Thanks :D

**Comment by Must57** [comment]
@strymsg Hi I try to use this tools too for azure but I can’t find a plugin. How do you use it on azure ?

Thanks, have a nice day.

**Comment by Swathi-Bhagwanji** [comment]
> Hi @wswebcreation , the screenshot is how the plugin shows the generated `index.html` file. useCDN looks good it did the trick with the css/js resources.
> 
> ![image](https://user-images.githubusercontent.com/35537786/194641608-fe9824a9-983c-4bdc-b7af-e7f6aafe7b01.png)
> 
> Regarding the feature/*.html files I used the workaround mentionend before and it is all properly displayed in the pipeline. Thanks :D

Can you please share the code to merge the feature/*html , i am stuck on same issue where i cannot follow the <a href="...">

**Comment by strymsg** [comment]
@Swathi-Bhagwanji this a function I used to merge all feature files and `index.html` to an `index-multiple.html`. Hope it helps
```typescript
const fs = require('fs');
const cheerio = require('cheerio');
const path = require('path');

/**
 * Merges scenario index.html and all html feature files generated by multiple-cucumber-report
 * into a single HTML file. Saves the file as index-multiple.html
 * @param reportPath Report path
 */
function mergeHtmlWithFeatureFiles(reportPath) {
  const htmlContent = fs.readFileSync(path.join(reportPath, 'index.html'), { encoding: 'utf8', flag: 'r' });
  const $ = cheerio.load(htmlContent);
  let aTags = $('a').toArray();
  aTags = aTags.filter((a) => {
    if (a.attribs && a.attribs.href) if (a.attribs.href.match(/features\//)) return a;
  });
  const filenames = [];
  for (const atag of aTags) {
    filenames.push(atag.attribs.href);
    atag.attribs.href = `#${atag.attribs.href.split('features/')[1].split('.html')[0]}`;
  }
  let featureContentsToCopy = '';
  for (const filename of filenames) {
    let htmlFeatureContent;
    try {
      htmlFeatureContent = fs.readFileSync(path.join(reportPath, filename), { encoding: 'utf-8', flag: 'r' });
    } catch (err) {
      throw new Error(`File ${filename} could not be read: ${err.message}`);
    }
    const featureContent = cheerio.load(htmlFeatureContent);
    featureContentsToCopy += `<hr><div id="${filename.split('features/')[1].split('.html')[0]}">`;
    featureContentsToCopy += featureContent('div.main_container').html();
    featureContentsToCopy += '</div>';
  }
  // copying the elments right after the last <div> tag of the html body
  $('div.row').last().after(`<div id="features">${featureContentsToCopy}</div>`);
  try {
    fs.writeFileSync(path.join(reportPath, 'index-multiple.html'), $.html(), { enconding: 'utf-8', flag: 'w' });
  } catch (err) {
    throw new Error(`Error writing file: ${err}`);
  }
  console.log(`${$.html().length} bytes saved.`);
  return path.join(reportPath, 'index-multiple.html');
}


```

**Comment by Swathi-Bhagwanji** [comment]
Thanks a lot for sharing the code :)

I still get further errors, lets see how it goes
