### ISSUE TITLE
Can we remove skipped tests from the report?

### ISSUE THREAD

**Issue by viralfineos** [wswebcreation/multiple-cucumber-html-reporter#223]
After my test fails I want to exit the script and when the html report is generated I don't want it to include the scripts that were skipped in the report. Can anyone help with this?

**Comment by wswebcreation** [comment]
Hi @viralfineos 

This report will only transform the JSON into HTML. If you want to remove data from the JSON then you need to do that yourself before you kick off this report.

Closing this now because it's not related to what the report can do for your
