### ISSUE TITLE
Allow some way to customize attachment names

### ISSUE THREAD

**Issue by rjktcby** [wswebcreation/multiple-cucumber-html-reporter#24]
Hi! Found reports generated by this project really cool. I'm planning to have multiple attachments of various types for some scenario steps. As of now they are all named by their type (**Screenshot+**, **Show info+**, etc)

Would be great if there will be a possibility to override these default names. When having multiple attachments of the same type it would be super helpful to know what's in each one of them.

I expect this to require some work for cucumber runners when generating reports, but for example with **cucumber-js** I believe extra fields could be easily added to report json using custom formatter.

Right now we have:
```
{
    "data":"",
    "media": {
        "encoding": "base64",
        "type": "image/png"
    }
}
```

Maybe support something like this?
```
{
    "data":"",
    "media": {
        "encoding": "base64",
        "type": "image/png"
    },
    "name": "My custom attachment"
}
```

or this:
```
{
    "data":"",
    "media": {
        "encoding": "base64",
        "type": "image/png",
        "name": "My custom attachment"
    }
}
```

not sure right now which one of these options would be cleaner for cucumber integration

**Comment by wswebcreation** [comment]
Hi @rjktcby 

I understand what you want but with the current json file generated by Cucumber (at least the JS version I'm using) this is not possible. This first needs some work on the Cucumber side and then I can implement this in the module. 

For now I'm going to close this, it's still open for discussion
