### ISSUE TITLE
Presenting total number of passed/failed tests in addition to percentage

### ISSUE THREAD

**Issue by jacekokrojek** [wswebcreation/multiple-cucumber-html-reporter#29]
Hi 

Thanks for creating awesome reporter. You did a great job. I have small suggestion that might be helpful. 
When I check the reports I am often interested in total number of failed tests/scenarios. Currently I can see only percentage values. I noticed that percentages are presented in table and also on the graph tooltip. I wonder if it is possible to present total number of passed/failed/etc test cases on the tooltip. That would be consistent with total number of all test/scenarios that are presented in the middle of the graph and give possibility to assess results in different dimension.

![obraz](https://user-images.githubusercontent.com/5174348/36248413-ab306f22-1237-11e8-93e9-27cbfea282fe.png)

**Comment by wswebcreation** [comment]
Hi @jacekokrojek 

Tnx for the compliments. If you want you can also contribute to the project by creating a PR, it won't be that hard I think. Please check the [CONTRIBUTING](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/master/docs/CONTRIBUTING.md) for more info.

**Comment by wswebcreation** [comment]
Is fixed in version [v1.6.0](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/master/CHANGELOG.md#160-2018-03-05)
