### ISSUE TITLE
Wrong format duration

### ISSUE THREAD

**Issue by yoghi** [wswebcreation/multiple-cucumber-html-reporter#32]
``
moment.utc(ms).format('HH:mm:ss.SSS');
``

I think that must be **ns** as declared in this thread of cucumber-js https://github.com/cucumber/cucumber-js/issues/1026 ; all implementation of cucumber seem use **ns** 

What do you think @LennDG @wswebcreation ?

**Comment by wswebcreation** [comment]
Hmm, strange, CucumberJS used *ns* in version 1, then changed it to *ms* in 2 and there is a difference now with other implementations.....
@yoghi , do you have a good way to distinguish *ns* and *ms* from each other when calculating the time?

**Comment by LennDG** [comment]
I developed this for Cucumber-js 3.0 mainly, I was not aware that 4.0 reverted back to ns (which is in my opinion pretty useless).

Maybe an option should be added to

**Comment by yoghi** [comment]
@wswebcreation i think is not possible detect automaticly ms or ns, it could be create a input parameters with default ns (choose from all implementation of cucumber). Using ns as default it's possible integrate this lib with json producted by other cucumber lib languages.

@LennDG I haven't seen on json spec the cucumber version.

**Comment by wswebcreation** [comment]
@yoghi and @LennDG 

I like the suggestion of @yoghi by adding a parameter like this

`durationInMS: true`

With this documentation


=======================================================================

### `displayDuration`
- **Type:** `boolean`
- **Mandatory:** No

If set to `true` the duration of steps, scenarios and features is displayed on the Features overview and single feature page in an easily readable format.
This expects the durations in the report to be in nanoseconds, which might result in incorrect durations when using a version of Cucumber that does not report in nanaseconds. This can be changed to milliseconds by adding the parameter `durationInMS: true`, see below

### `durationInMS`
- **Type:** `boolean`
- ***Default:* `false`
- **Mandatory:** No

If set to `true` the duration of steps will be expected to be in milliseconds, which might result in incorrect durations when using a version of Cucumber that does report in nanaseconds. This can't be calculated automatically.
This parameter relies on `displayDuration: true`
=======================================================================

What do you guys think?

When agreed I'll add this after PR https://github.com/wswebcreation/multiple-cucumber-html-reporter/pull/31 is merged.

**Comment by LennDG** [comment]
Seems good, funny typo though.

> which might result in incorrect durations when using a version of Cucumber that does report in *nanaseconds*

**Comment by wswebcreation** [comment]
@LennDG hahaha, updated the comment, tnx

**Comment by yoghi** [comment]
:thumbsup:

**Comment by humphreyn** [comment]
They reverted to nanoseconds to bring cucumber-js in-line with all other implementations. Which IMO is a good thing.  It also means report generators can use the same standard

**Comment by wswebcreation** [comment]
Tnx, I saw it yeah, I'll create a fix as described above, will do that this week hopefully

**Comment by humphreyn** [comment]
That would be great as I will be giving a demo to my my team along with NightwatchJS, CucumberJS to convince them to use this tech stack rather than JBehave

**Comment by muthukumarse** [comment]
@wswebcreation - hope you had time to fix. 

cheers

**Comment by wswebcreation** [comment]
I've release version 1.7.0 and updated the docs. Going to close it for now, if there are any issues with it please open a new ticket
