### ISSUE TITLE
Wrong passed/failed tool-tip in features box

### ISSUE THREAD

**Issue by damonpam** [wswebcreation/multiple-cucumber-html-reporter#33]
Current state:
![captura realizada el 2018-03-08 10 01 50](https://user-images.githubusercontent.com/12949398/37142245-cb59b2be-22b7-11e8-98d1-08cbe4ad90ec.png)

Expected behaviour:
Feature passed/failed

**Comment by wswebcreation** [comment]
Hi @damonpam 

Tnx for this. I've fixed it with version [1.6.1](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/master/CHANGELOG.md#161-2018-03-12)
