### ISSUE TITLE
Export parsing functions

### ISSUE THREAD

**Issue by jacekokrojek** [wswebcreation/multiple-cucumber-html-reporter#41]
Hi again

I am using [CucumberJS Slack Bot](https://www.npmjs.com/package/cucumberjs-slack-bot) and I noticed that it incorrectly parses Cucumber JSON report. I would like to update this module and reuse parsing functions from multiple-cucumber-html-reporter. I thought that add dependency to multiple-cucumber-html-reporter and use its parse functions would be a good idea but as far as I know Java parsing functions are not exported. I would like to ask to export those functions so I can easily use them outside of reporter or propose some other way to reuse those functions.

Jacek

**Comment by wswebcreation** [comment]
Hi @jacekokrojek 

Can you please explain more what you need? This plugin only needs:

- be run in nodejs
- a Javascript script to tell where the report files can be located and how the report should look like

**Comment by jacekokrojek** [comment]
Indeed, this plugin generates report. In order to do this it parses json files and prepares raw statistics which are stored in suite variable by various _parse... functions. I would like to be able to use suite variable in other project. 

To present issue from different angle it would be helpful for me if multiple-cucumber-html-reporter could contains 2 submodules: json file parser that return suite object and report generator that uses suite object. Having this I could use json parser submodule to generate results that later could be sent to slack.

**Comment by wswebcreation** [comment]
Sorry for my late reaction, can you create a PR for this with what you want?
