### ISSUE TITLE
Inconsistency Git Repo and NPM Package

### ISSUE THREAD

**Issue by LennDG** [wswebcreation/multiple-cucumber-html-reporter#49]
When generating a report while using the package from NPM (^1.10.0) the duration of fields is incorrectly displayed (all set to 00:00:00:00.000) when using `durationInMS` set to true.

When trying to replicate this issue with the code pulled from Github the durations were correctly set.

I am not sure where exactly the bug is located, however I think that some sort of synchronization issue is present.

**Comment by wswebcreation** [comment]
Hi @LennDG 

This is strange, it hasn't changed since I think 1.8.0 if I check the changelog and the comparisons. Can you also post a link to your files on gist?

When I check my version I get this

**My version in my project**
![image](https://user-images.githubusercontent.com/11979740/39856379-fcb51db8-542f-11e8-9b90-758f0800588c.png)


**Overview**
![image](https://user-images.githubusercontent.com/11979740/39856345-c792da58-542f-11e8-9f30-ca544b64d56d.png)

**Scenario's**
![image](https://user-images.githubusercontent.com/11979740/39856358-ddf698ac-542f-11e8-87e1-a8edda7782c6.png)

**Comment by LennDG** [comment]
Had a long weekend, will update soon.

**Comment by wswebcreation** [comment]
Hi @LennDG 

Do you already have more info?

**Comment by LennDG** [comment]
Totally forgot! Had some busy times.

The package.json specifies to use 1.10.0, which is the latest version if I am correct. For the example I am using a fully fresh install.
![package](https://user-images.githubusercontent.com/5593865/40469013-7ada04ce-5f2f-11e8-926f-78eca6805383.PNG)

My I have a test.js file that specifies to use `durationInMs` since that is what I need. You can see it in this image:
![test](https://user-images.githubusercontent.com/5593865/40469208-015e3a6a-5f30-11e8-9b38-f812a333b262.PNG)

The files I am using are the failure_report jsons that are in the test data on the git repo.

While testing again however I have run in to strange behaviour. 
failure_report_v1 seems to displays the durations correctly as seen here (although we should do a check for skipped steps, it is not conform to the rest) : 
![f1](https://user-images.githubusercontent.com/5593865/40469854-1bc7c1a8-5f32-11e8-88cd-68e0a732883d.PNG)
On further investigation it just appears that way since that test has a duration of 30 hours.

failure_report_v2 and v3 do not display correctly either, showing 0 accross the durations:
![f1](https://user-images.githubusercontent.com/5593865/40469948-5fb87452-5f32-11e8-95df-752a426ffa2b.PNG)

I am fairly certain that this happens due to an incorrect conversion for the durations.

When testing this with the code pulled from git, the issue does not appear when running test.js. 
![f1_test](https://user-images.githubusercontent.com/5593865/40470210-22fe493c-5f33-11e8-84e7-923e86a02911.PNG)

This test has however shown a second bug that tests that take more than one day overflow and loop back (the actual total duration is 30 hours and not 6).

I hope this sufficiently shows that there is a difference between the git repo and the npm package, if you need any more information just ask!

**Comment by wswebcreation** [comment]
Hi @LennDG 

Tnx for this, I need to dive into this, but I'm also kinda busy ;-). Hope to pick this up somewhere next week

**Comment by LennDG** [comment]
So I had some time to dive into it and I noticed that it was me that did something wrong. Instead of ```durationInMS``` I wrote ```durationInMs``` which caused it to be incorrectly displayed.

My fault for not copying correctly!

**Comment by wswebcreation** [comment]
Lol,

I didn't got time to do more investigation but good you found out.
