### ISSUE TITLE
Feature being shown as passed when there is no code written for it

### ISSUE THREAD

**Issue by larryg01** [wswebcreation/multiple-cucumber-html-reporter#50]
It would be great to have the Feature Status shown as Undefined or Pending 
(i.e. 1. if there is a feature file WITHOUT a step_definition file then it should show as Undefined
2. if there is a feature file WITH a step_definition file but no REAL code then it should show Pending)
in addition to how it works now.

**Comment by wswebcreation** [comment]
Hi @larryg01 

You are right, it would be nicer if we have that already in our overview. But how would you see it when a feature has a:

- succeeded
- pending

scenario? What should the status be then? Care for a PR?
