### ISSUE TITLE
Multiple empty features are being added to the main report page

### ISSUE THREAD

**Issue by kappa10j** [wswebcreation/multiple-cucumber-html-reporter#51]

**Comment by wswebcreation** [comment]
Can you please specify your issue with more info, provide your json files and so on. I can't do anything with this.

**Comment by wswebcreation** [comment]
@kappa10j 

Can you please provide more info, if not I'm going to close this issue after the weekend

**Comment by kappa10j** [comment]
sorry.. i'm not seeing it anymore.  I'm not sure what I did to cause it to
happen.
