### ISSUE TITLE
TypeError: CollectJSONS

### ISSUE THREAD

**Issue by FlippieCoetser** [wswebcreation/multiple-cucumber-html-reporter#56]
When running `wdio` with: 
` onComplete: () => {report.generate({jsonDir: './report/',reportPath: './report/' });}`

The report.json, produced by wdio, is correctly loaded:  
 `const data = fs.readFileSync(file).toString() || "[]";` (collect-json.js:22)

Yet a TypeError: `JSON.parse(...).map is not a function` is received. (collect-json.js:23)

Any help would be appreciated.

**Comment by wswebcreation** [comment]
Hi @FlippieCoetser 

I didn't have a look at it yet because I was to busy releasing my webdriver.io version of this report. Maybe you can have a look at that one ;-)

https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter

You can then also use it with the latest version of Cucumber

**Comment by FlippieCoetser** [comment]
@wswebcreation the new wdio reporter just works ;-) I will close this issue.
