### ISSUE TITLE
Use OS from capabilities?

### ISSUE THREAD

**Issue by faceleg** [wswebcreation/multiple-cucumber-html-reporter#57]

**Comment by wswebcreation** [comment]
Hi,

Can you please provide more info and a possible solution?

**Comment by faceleg** [comment]
Sorry! 

I've updated my report.hook.js (Have to lock wdio-cucumber... to 1.0.0 because later versions break scenario outlines):

```js
      const valueOrUnknown = (value) => value ? value : 'unknown'
      let device = capabilities.device
      if (!capabilities.device) {
        device = `${capabilities.os} ${capabilities.os_version}`
      }

      jsonReport[0].metadata = {
        browser: {
          name: valueOrUnknown(capabilities.browserName),
          version: capabilities.device
            ? capabilities.os_version
            : capabilities.browser_version,
        },
        device: device,
        platform: {
          name: valueOrUnknown(capabilities.os),
          version: valueOrUnknown(capabilities.os_version),
        },
      }
```

Results in the below format when using browserstack

![screen shot 2018-07-25 at 8 48 36 am](https://user-images.githubusercontent.com/1000759/43165276-9d1657d4-8fe7-11e8-8c6f-9da93356e74e.png)

**Comment by wswebcreation** [comment]
Hi @faceleg 

Maybe I'm missing something, but is there an issue now?

**Comment by wswebcreation** [comment]
Going to close this one due to inactivity
