### ISSUE TITLE
Scenario names within a feature file have duplicate names in the html report

### ISSUE THREAD

**Issue by gurunanakdevji** [wswebcreation/multiple-cucumber-html-reporter#62]
Scenario names within a feature file have duplicate names in the html report.
Actually, the name of the last scenario executed in a feature file is used as name of all the scenarios in the report. Checked the JSON file and see that all scenario names are duplicate. This issue need fixing on priority.

**Comment by wswebcreation** [comment]
@gurunanakdevji 

Can you please fill in the issue template and provide all the info, the one I think you removed when you filed this issue

But based on your info, this is **not** an issue in the module but in the **output** you are using, you say

>  Checked the JSON file and see that all scenario names are duplicate.

This module does nothing with the output itself, it only collects all the jsons and creates a nice report

**Comment by gurunanakdevji** [comment]
Thanks a lot for your reply. Actually i am using webdriverio and chose the
report tool as provided use and in report otions i gave path of creation of
json and report. So is it wdio is responsible for json creation??

**Comment by wswebcreation** [comment]
@gurunanakdevji 

Please file an issue [here](https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter) if you'd like and also provide the needed info there. 

I'm going to close it here
