### ISSUE TITLE
The html report is not generated after the tests have finished, even though the json files are generated correctly in the specified path

### ISSUE THREAD

**Issue by CTMarius** [wswebcreation/multiple-cucumber-html-reporter#63]
**Environment:**
 - multiple-cucumber-html-reporter: 1.11.2
 - Node.js version: 8.11.1
 - NPM version: 5.6.0
 - Platform name and version: Windows 10
 - Cucumber version: 5.0.0

**Config of protractor + multiple-cucumber-html-reporter**

- Configuration file: 
```
exports.config = {
	onPrepare: function () {
		'use strict';		
		require('babel-core/register');		
		browser.getCapabilities().then(function (capabilities) {
			browser.browserPlatform = capabilities.get('platform');
			browser.browserName = capabilities.get('browserName');
			browser.browserVersion = capabilities.get('version');
		});
	},
	framework: 'custom',	
	frameworkPath: require.resolve('protractor-cucumber-framework'),
	cucumberOpts: {		
		require: ['../features/step_definitions/*.js', '../features/support/*.js'],
		format: 'json:dist/teste2e/report/report2/report.json'
	},
	specs:['../features/*.feature'],	
	directConnect: false,
	jasmineNodeOpts: {
		defaultTimeoutInterval: 250000
	}
};
```

- Reporter Hook:
```
module.exports = function () {
	'use strict';
	const report = require('multiple-cucumber-html-reporter');
	this.AfterFeatures(function(callback) {
		report.generate({
			jsonDir: './teste2e/report/',
			reportPath: './teste2e/report/',
			metadata:{
				browser: {
					name: browser.browserName,
					version: browser.browserVersion
				},
				device: 'Local test machine',
				platform: {
					name: browser.browserPlatform,					
				}
			}
		});
		callback();
	});
};
```

**Bug description**
The html report is not generated after the tests have finished, even though the json files are generated correctly in the specified path. 

The following error is displayed in the console after the test finish running:
```
[14:35:56] E/launcher - Unexpected token e in JSON at position 0
[14:35:56] E/launcher - SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at step.embeddings.forEach (<path>\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:329:67)
    at Array.forEach (<anonymous>)
    at scenario.steps.forEach.step (<path>\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:326:25)
    at Array.forEach (<anonymous>)
    at _parseSteps (<path>\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:321:20)
    at feature.elements.forEach.scenario (<path>\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:250:18)
    at Array.forEach (<anonymous>)
    at _parseScenarios (<path>\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:240:22)
    at suite.features.forEach.feature (<path>\node_modules\multiple-cucumber-html-reporter\lib\generate-report.js:186:17)
[14:35:56] E/launcher - Process exited with error code 199

```
The issue seems to be with the following line in the generate-report.js file where json.parse is used:
`step.text = (step.text ? step.text : []).concat([JSON.parse(embedding.data)]);`

**Expected behavior**
A index.html file should be generated in the report folder.

**Possible fix**
I've replaced json.parse with json.stringify and the report was generated successfully. 

`step.text = (step.text ? step.text : []).concat([JSON.stringify(embedding.data)]);`

**Additional details**
I could also reproduce this issue with the latest version of protractor-multiple-cucumber-html-reporter-plugin.
[report.txt](https://github.com/wswebcreation/multiple-cucumber-html-reporter/files/2375342/report.txt)

**Comment by wswebcreation** [comment]
Hi @CTMarius 

Tnx for filing an issue and all the data, it's really helpful. To know if the solution you provided would also work it would be nice if you can also provide the json files so I can also test it. If yo like you can also create a PR ;-)

**Comment by CTMarius** [comment]
Hi @wswebcreation 
I attached the json to the original issue. I renamed the file to report.txt since github doesn't allow me to attach .json files. I also edited the "uri" field for privacy reasons. 

Regarding the PT, I wasn't sure if I should make a PR directly or submit an issue, thanks for letting me know,

**Comment by wswebcreation** [comment]
Tnx for the PR, I'll look at it tomorrow.

**Comment by CTMarius** [comment]
Fix merged. Closing issue.
