### ISSUE TITLE
generate-report.js calculates time wrongly as Cucumber 4 returns time in nano seconds

### ISSUE THREAD

**Issue by vvedachalam** [wswebcreation/multiple-cucumber-html-reporter#65]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.10.1
 - Node.js version: 10.1.0
 - NPM version: 5.6.0
 - Platform name and version:  Ubuntu
 - Cucucmber version: 4.2.1

**Config of TestCafe + multiple-cucumber-html-reporter**
"node report-generator.js",

**Describe the bug**
When we create the report, though the tests run only for 10-15 seconds, the duration is displayed in hours in the report. 
Digging down the issue, I found that the below code considers the time in MS though cucumber returns in nano second
return moment.utc(durationInMS ? ns : ns / 1000000).format('HH:mm:ss.SSS');
If I change the code to the one as mentioned below, all works fine
return moment.utc( ns / 1000000).format('HH:mm:ss.SSS');

**To Reproduce**
Run the tests with Cucumber 4 version

[Include code or an example repository that can easily be set up]

**Expected behavior**
Not sure why the durationInMS is not failing and ns condition is getting invoked to convert nano to milli seconds

**Comment by wswebcreation** [comment]
Hi @vvedachalam 

Can you please provide the config of how you run the report? It looks like you're not passing correct options to the reporter.

**Comment by vvedachalam** [comment]
@wswebcreation Thanks for the quick reply.

The Config that i use is:

const report = require('multiple-cucumber-html-reporter');
const path = require('path');
const projectName = path.basename(__dirname);
const projectVersion = process.env.npm_package_version;
const reportGenerationTime = (new Date()).toISOString();
report.generate({
    reportName: 'Vijay Report',
	jsonDir: 'reports',
    reportPath: 'reports',
    openReportInBrowser: false,
    disableLog: true,
    displayDuration: true,
    durationInMS: true,
    customData: {
        title: 'Run info',
        data: [
            {label: 'Project', value: `${projectName}`},
            {label: 'Release', value: `${projectVersion}`},
            {label: 'Report Generation Time', value: `${reportGenerationTime}`},
            
        ]
    }
});

Also I have set the below:
  const displayDuration = options.displayDuration || false;
  const durationInMS = options.durationInMS || false;

**Comment by vvedachalam** [comment]
Yes, just noticed that after you have mentioned. I was looking into the package and forgot to check my config. Thanks a lot for the quick response. I am happy to close this

**Comment by wswebcreation** [comment]
@vvedachalam 

Cool, tnx and good luck with using the module!

**Comment by vvedachalam** [comment]
@wswebcreation Thanks, its really so handy. One quick Q. The report is not fetching the values Devices, Browser and OS. Could you please let me know where to set that up?

**Comment by vvedachalam** [comment]
@wswebcreation Cool. Thanks
