### ISSUE TITLE
 [openReportInBrowser] Never call callback on Mac os

### ISSUE THREAD

**Issue by mrakibmiah** [wswebcreation/multiple-cucumber-html-reporter#67]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: latest
 - Node.js version:v8.10.0
 - NPM version: 5.8.0
 - Platform name and version: MacOs
 - Cucucmber version: 4.0.0

**Config of custom framework + multiple-cucumber-html-reporter**
    const options = {
        jsonDir: REPORTS_PATH + "/",
        reportPath: REPORTS_PATH + "/",
        openReportInBrowser: true,
        displayDuration: true,
        customMetadata: true,
        saveCollectedJSON: true,
    };

**Describe the bug**
After generating a report and open the browser, process got stuck and never terminate the node process on MacOS

This is the relevant ticket for opn package  https://github.com/sindresorhus/opn/issues/91
issue resolved on this ticket https://github.com/sindresorhus/opn/issues/92

this is the place where it got stuck https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/master/lib/generate-report.js#L150

**To Reproduce**
1. configure openReportInBrowser: true,
2. Generate report

[Include code or an example repository that can easily be set up]

**Expected behavior**
Node process should be terminated after opening the browser without CTRL + C. open browser [opn package], promise should be resolved on MacOS.

**Comment by wswebcreation** [comment]
Thanks for filing the issue. Care for a PR?

**Comment by BaCaRoZzo** [comment]
@wswebcreation what do you think about closing this issue?
The fix in the dependency has been release in `6.0.0` and since you depend on `^7.0.2` the fix is already in.
At the end of the day, no one complained in 4 years, I don't really think anyone is starting to do so after you close the issue. 😄

**Comment by wswebcreation** [comment]
Good one, let’s close it
