### ISSUE TITLE
Is it possible to group features in the REPORT HTML based on the feature folder

### ISSUE THREAD

**Issue by id4automation** [wswebcreation/multiple-cucumber-html-reporter#68]
My test automation library got implementations for multiple widgets in the application. Hence I created independent folders to group the respective feature file. When I run the wdio-multiple-cucumber-html-reported, it combines all feature file into one big list . Is it possible to retain the same folder structure?

I would prefer to see all the feature files listed under their respective folder name.
It would be nice to have expand and collapse of features by using the folder names

Previously I used allure report and migrating now to this multiple html reporter. Would be nice to have this feature included that helps the BA and Project team to go through their folders to locate the specific feature file

**Comment by wswebcreation** [comment]
Sorry for my late response,

Do you also save the files in separate folders? 
This module will read the JSON files from a folder, but does nothing with folder structure or what so ever. I also wonder how I should handle that in the frontend. What are your ideas about that?

**Comment by id4automation** [comment]
Hi,

Yes, I stored the feature files in their respective folder.Hence folder will have their 4,5 feature files.  Please find the snipped of one such feature file

{
      "keyword": "Feature",
      "description": "    As a user on the Fidelity Finance wellness \n    I want to launch the link\n    SO THAT I can carry out the successful validation",
      "line": 1,
      "name": "Landing Page",
      "tags": [],
      "uri": "C:\\xxxxxxx\\xxxxx\\qa\\src\\features\\**financeWellness**\\landing.feature",
      "elements": [],
      "id": "landing-page",
      "metadata": {
         "browser": {
            "name": "Google chrome",
            "version": "69.0.3497.100 (Official Build) (64-bit)"
         },
         "device": "Lenova X1 Carbon",
         "platform": {
            "name": "Windows 10",
            "version": "Windows 10 Enterprise"
         }
      }

Is there any way we can do any of the below choices?
1. Create a seperate variable [like "groupname":"<folderName where feature file resides>"]  in the above object with tag name corresponds to parent folder name from uri
2. Based on the variable, grouping all the common groups in the UI . I am expecting to see the feature reports as a list under their respective group name. This could be expanded and collapsed.   OR an additional column display the group name , so can atleast group them together by clicking on the column header .
3. Having as a cucumber report option to either enable this feature folder structure.


PS: Do I need to raise the PR ? If so, let me know how to do it as I cant find any options and never did it before.

**Comment by id4automation** [comment]
Hi, I forked your repository and implemented the options 2 and 3 and sent you a pull request for you to review. Kindly check the same. I tried it with a json file with folder names and it works as expected. When there is a folder name after features\widgetOrProjectFolderName\one.feature I am seeing widgetOrProjectFolderName. Looking forward to hear from you.

![image](https://user-images.githubusercontent.com/41796998/47506478-09f43d80-d868-11e8-864b-d9ec12db0d26.png)
