### ISSUE TITLE
Possibility to add global metadata

### ISSUE THREAD

**Issue by Doschdn1** [wswebcreation/multiple-cucumber-html-reporter#7]
Hi,

insead of manipulating each JSON File before creating the report it would be much easier (like in cucumber-html-report) to set the metadata for all files via options.

Code from cucumber-html-report:

var options = {
        jsonFile: 'test/report/cucumber_report.json',
        output: 'test/report/cucumber_report.html',
        metadata: {
                "browser": {
                    "name": "chrome",
                    "version": "58"
                },
                "device": "desktop",
                "platform": {
                    "name": "Windows",
                    "version": "7"
                }
        }
    };

**Comment by wswebcreation** [comment]
Hi @Doschdn1 ,

Thanks for your issue. The difference between cucumber-html-report and my report module is that it can handle multiple different browsers. When you use a global, how can you assign chrome to report 1 and firefox to report 2?

**Comment by Doschdn1** [comment]
Hi, 

thats true, but when i perform whole testsuits only on a single browser version this would be much better if i could give the metadata with the options instead of setting 'not known' in collect-jsons.js

...   
 files.map(file => jsonFile.readFileSync(file).map(json => {
        json = Object.assign({
            "metadata": {
                "browser": {
                    "name": "not known",
                    "version": "not known"
                },
                "device": "not known",
                "platform": {
                    "name": "not known",
                    "version": "not known"
                }
            }
        }, json);
        ...

**Comment by wswebcreation** [comment]
See also https://github.com/wswebcreation/multiple-cucumber-html-reporter/issues/6 with a reference to how you could solve it.

In this module I don't see a lot of advantage in adding this in the global because the focus here is more on multiple browsers, that's why I used the name `multiple` ;-).

I'm going to close this issue now because this has more to do on how you want to use the module and providing the data to the module.

**Comment by wswebcreation** [comment]
@Doschdn1 

With more and more people using this module I implemented your wish in version 1.0.0, see also [here](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/master/CHANGELOG.md#100-2017-09-08).

Hope you like it

**Comment by humphreyn** [comment]
Hi,
My solution for this was to extend the JSON formatter to automatically add the metadata. The metadata itself is captured by a hook at run time. The framework I am using is NightwatchJs

The hook looks like this:
****************************************************************************************
const {Before}    = require('cucumber');
const { client }  = require('nightwatch-cucumber');
const metadataHelper = require('../../lib/metadataHelper');

Before(function (callback) {
  //Only need to get metadata once in test session
  //cannot do this in BeforeAll as this(world) is not available in BeforeAll/AfterAll hook
  if(!client.globals.metadata) {
    metadataHelper.get()
      .then((metadata) => {
        client.globals.metadata = metadata;
        callback;
      });
  }
});

************************************************************
The metadata helper looks like this  and requires the useragent npm module

const userAgent = require('useragent');
const config = require('config');
const { client } = require('nightwatch-cucumber');


/**************************************************
 * Returns capabilities metadata
 *
 */
function get() {
  return getUserAgent()
    .then((result) => {
      const agent = userAgent.parse(result);
      const metadata = {
        "browser": {
          "name": client.capabilities.browserName,
          "version": (client.capabilities.browserName === 'chrome') ? client.capabilities.version : client.capabilities.browserVersion
        },
        "device": (agent.device.family === 'Other') ? config.get('environment') : client.device.family,
        "platform": {
          "name": getPlatformName(agent.os.family),
          "version": getPlatformVersion(agent.os)
        }
      };
      return metadata;
    });
}

function getUserAgent() {
  return new Promise((resolve, reject) => {
    client.execute(function() {
      return window.navigator.userAgent;
    }, [], function(result) {
      if(result.status === 0) {
        resolve(result.value);
      }
      else {
        reject();
      }
    });
  });
}


function getPlatformName(osFamily) {
  const platform = osFamily.split(' ')[0].toLowerCase();

  if (platform.includes("win")) {
    return "windows";
  }
  else if (platform.includes("nux") || platform.includes("nix")) {
    return "linux";
  }
  else if (platform.includes("mac")) {
    return "ios";
  }
  else {
    return platform;
  }
}

function getPlatformVersion(agentOS)  {
  const idx = agentOS.family.indexOf(' ');

  if(idx >= 0 ) {
    return agentOS.family.substr(idx + 1);
  } else {
    return `${agentOS.major}.${agentOS.minor}.${agentOS.patch}`;
  }

}

module.exports = {
  get
};

************************************************************
Then my extended json formatter looks like this:

const JsonFormatter = require('cucumber').JsonFormatter;
const { client } = require('nightwatch-cucumber');
const fs = require('fs-extra');
const jsonFilePath =  require('./htmlReport').jsonFilePath;

class ExtendedJsonFormatter extends JsonFormatter {

  constructor(options) {
    super(options);
    options.eventBroadcaster.on('test-run-finished', this.setMetaData);
  }


  async setMetaData() {
    const contents = await fs.readJson(jsonFilePath);

    // Add metadata for each feature
    for (let i = 0; i < contents.length; i++) {
      contents[i].metadata = client.globals.metadata;
    }

    fs.writeJsonSync(jsonFilePath, contents);
  }
}
module.exports = ExtendedJsonFormatter;

********************************************************

I therefore do not need to add any properties in the config or run any post processing steps to add the correct metada info.

**Comment by wswebcreation** [comment]
@humphreyn ,

Tnx for sharing!
