### ISSUE TITLE
Unable to generate report getting following error

### ISSUE THREAD

**Issue by guptarajatkn** [wswebcreation/multiple-cucumber-html-reporter#73]
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.11.4
 - Node.js version: v10.4.0
 - NPM version: 6.1.0
 - Platform name and version: MacOsX
 - Cucucmber version: 5.0.2

**Config of wd + cucumber + multiple-cucumber-html-reporter**
var reporter2 = require('multiple-cucumber-html-reporter');

**Describe the bug**
Unable to generate report from a single json file available at the path, was working previously,
able to gererate html for same .json by cucumber-html-reporter

**Expected behavior**
Should be able to generate report as the same cucumber-report.json is generating report by another npm package

**Log**

TypeError: JSON.parse(...).map is not a function
    at files.map.file (.../node_modules/multiple-cucumber-html-reporter/lib/collect-jsons.js:23:30)
    at Array.map (<anonymous>)
    at collectJSONS (.../node_modules/multiple-cucumber-html-reporter/lib/collect-jsons.js:20:15)
    at Object.generateReport [as generate] (.../node_modules/multiple-cucumber-html-reporter/lib/generate-report.js:67:23)
    at .../runtime/world.js:244:27
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Additional context**
Using a customised framework using cucumber+wd

**Comment by jonn-set** [comment]
I am having the same problem, I am using the wdio-json-reporter plugin to generate the json file, here my generated json file:

`{
  "start": "2018-12-03T17:05:18.133Z",
  "end": "2018-12-03T17:05:28.753Z",
  "capabilities": {
    "browserName": "chrome",
    "chromeOptions": {}
  },
  "host": "127.0.0.1",
  "port": 4444,
  "baseUrl": "http://localhost:8080",
  "framework": "cucumber",
  "mochaOpts": {
    "timeout": 10000
  },
  "suites": [
    {
      "name": "Google Test",
      "tags": [],
      "duration": 1095,
      "start": "2018-12-03T17:05:27.487Z",
      "end": "2018-12-03T17:05:28.582Z",
      "tests": [],
      "hooks": []
    },
    {
      "name": "Open Google",
      "tags": [],
      "duration": 1052,
      "start": "2018-12-03T17:05:27.529Z",
      "end": "2018-12-03T17:05:28.581Z",
      "tests": [
        {
          "name": "I am on Google home page",
          "start": "2018-12-03T17:05:27.531Z",
          "duration": 1223,
          "state": "pass"
        },
        {
          "name": "The title of the page is \"Blah\"",
          "start": "2018-12-03T17:05:28.559Z",
          "duration": 195,
          "state": "fail",
          "error": "expected Google to equal Blah ignoring case",
          "standardError": "AssertionError: expected Google to equal Blah ignoring case\n    at World.<anonymous> (/Users/john/workspace/webdriverio-tut/tests/features/step_definitions/google.steps.js:8:38)\n    at Promise.F (/Users/john/workspace/webdriverio-tut/node_modules/core-js/library/modules/_export.js:36:28)"
        }
      ],
      "hooks": []
    }
  ],
  "state": {
    "passed": 1,
    "failed": 1,
    "skipped": 0
  }
}`

If I wrap this json message in an array [], then it does not throw error but the report is blank, no scenarios number, no feature numbers, no pie chart, all numbers are just zero.

**Comment by wswebcreation** [comment]
@jonn-set

The the module needs to have a JSON created by CucumberJS, the json-report output will nog work

**Comment by jonn-set** [comment]
Sorry to bother your, but CucumberJs 4+ does not seem to generate json report by itself. In my config fie I have the following setting 

`cucumberOpts.format`:  ['json','pretty'] 
`reporterOptions.outputDir`: a valid path 
`reporters`: does not include 'json' as it starts looking for `wdio-json-reporter` and crashes out even before the tests start.

But wont generate the json, am I missing something here?

I know its not for you to sort this out, but I dont seem to get any answers about Cucumber generating its  own json reports anywhere. Any help will be greatly appreciated.

Thank you
John

**Comment by wswebcreation** [comment]
Hi @jonn-set 

You could still use the JSON file from CucumberJS, only WebdriverIO doesn't support exporting the JSON originally from CucumberJS. That's why I started creating [this module](https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter).
This module will create its own JSON file based on the steps that are executed. It could be that not all needed info is available, but that has to do with the _limitation_ of WebdriverIO and the data that is not provided by WebdriverIO.

So please check the [wdio-multiple-cucumber-html-reporter](https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter) module

**Comment by wswebcreation** [comment]
@jonn-set 

Just check [here](https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter#how-do-i-add-screenshots-to-the-report).
There is 1 limitation, each screenshot you make will be added to the report automatically. Reason is that I can't see the difference between a step / before / after hook, so I added all screenshots to the report.

Hope it fits your needs, please ask all questions/file all issues related to the module there.

Tnx

Grtz

Wim

**Comment by jonn-set** [comment]
Thanks Wim, I am already using the After hook to capture the screenshots, just thought would be nice to have the screenshot attached to the step itself, but haven't found a working solution yet, tried the `afterStep` hook as well but it fails to capture screenshot in it. 

After hook still works like a charm, so will stick to it for the time being. 

Thanks, appreciate your help so far.

**Comment by djwgit** [comment]
thanks for this nice reporting tool.
will be nice if could show the screenshots captured in afterstep hook, (as in jenkins cucumber-jvm report) ... thanks
