### ISSUE TITLE
Background tasks are considered as scenarios

### ISSUE THREAD

**Issue by lahiruchandima** [wswebcreation/multiple-cucumber-html-reporter#83]
In my cucumber feature files, there is a **Background**  scenario in most cases, which runs before each scenario (similar to @BeforeMethod in TestNG).

The  report generated by **multiple-cucumber-html-reporter** considers these tasks as scenarios as well, so the combined report shows a much higher total scenario count than there actually is.

Is there any way to exclude the  **Background**  scenarios?

**Comment by wswebcreation** [comment]
Hi @lahiruchandima 

Can you provide an example JSON file with the background steps? Because I think you will see that the background steps are shown as scenario steps because that is how Cucumber works.

This report only processes the JSON-files and calculates the failures/passed and so on

**Comment by AlexEzzeddine** [comment]
I have the same issue, here is my json ( I removed irrelevant information)
```
[  
  {
    "uri": "/test/test.feature",
    "id": "test",
    "keyword": "Feature",
    "name": "Test",
    "description": "",
    "line": 2,
    "tags": [],
    "elements": [
      {
        "keyword": "Background",
        "name": "",
        "description": "",
        "line": 4,
        "type": "background",
        "steps": []
      },
      {
        "id": "test-scenario",
        "keyword": "Scenario",
        "name": "Test Scenario",
        "description": "",
        "line": 11,
        "type": "scenario",
        "tags": [],
        "steps": []
      }
    ]
  }
]
```

**Comment by AlexEzzeddine** [comment]
Here is a screenshot
<img width="1648" alt="Screen Shot 2019-04-19 at 5 12 04 PM" src="https://user-images.githubusercontent.com/2828431/56448701-53c55a00-62c6-11e9-8bf9-d15b5d4183dc.png">

**Comment by wswebcreation** [comment]
Hmm,

I need to dive into this. The background was always created like this `"isBackground": true,` in a step and not as a separate scenario.

I'll set up some examples and try to fix this

**Comment by wswebcreation** [comment]
@AlexEzzeddine 

I've been checking this with CucumberJS 5 and I can't find the `"keyword": "Background",`. Can you provide:

- the version and language of Cucumber  you are using
- a better demo example of the background (with some steps and a feature file)
- explain what you expect to happen with the Background steps in the report

Tnx

**Comment by AlexEzzeddine** [comment]
I am actually using cucumber for ruby. Version is 2.4.0
I expect:
1. I expect background elements to show up in report as "Background:", not "Scenario:".
2. I expect them to not be included in any scenario counts. Example: I have 6 Background elements and 6 Scenarios. Total scenario count should be 6 and not 12.

**Comment by wswebcreation** [comment]
Sorry about this one.

Can you please provide a sample feature file and a sample json output so I can dig into this?

**Comment by jordansilva** [comment]
@wswebcreation 
```
{
    "line": 2,
    "elements": [
        {
            "line": 4,
            "name": "",
            "description": "",
            "type": "background",
            "keyword": "Background",
            "steps": [
                {
                    "result": {
                        "duration": 5032682000,
                        "status": "passed"
                    },
                    "line": 5,
                    "name": "I am logged in",
                    "match": {
                        "location": "iLoggedIn()"
                    },
                    "keyword": "Given "
                }
            ]
        },
        {
            "start_timestamp": "2019-08-12T16:22:35.079Z",
            "before": [],
            "line": 8,
            "name": "Scenario 01",
            "description": "",
            "id": "scenario01",
            "after": [],
            "type": "scenario",
            "keyword": "Scenario",
            "steps": [],
            "tags": []
        },
    ],
    "name": "Feature 01",
    "description": "",
    "id": "feature01",
    "keyword": "Feature",
    "uri": "file:features/feature01.feature",
    "tags": []
}
```

**Comment by Apolayo27** [comment]
any solution for this error?
