### ISSUE TITLE
Datatable in scenario

### ISSUE THREAD

**Issue by bevinahal** [wswebcreation/multiple-cucumber-html-reporter#91]
Currently, datatables are not available in the feature file html. Can you please add this feature?

**Comment by bevinahal** [comment]
Using cucumber java to generate json

**Comment by bevinahal** [comment]
https://github.com/cucumber/cucumber-jvm/blob/master/core/src/main/java/cucumber/runtime/formatter/JSONFormatter.java

JSON formatter

**Comment by wswebcreation** [comment]
@bevinahal 

Thanks for mentioning this. Can you please provide an example json in a Gist? Thanks
