### ISSUE TITLE
How to disable browser/device metadata for non-browser tests? 

### ISSUE THREAD

**Issue by agliolio** [wswebcreation/multiple-cucumber-html-reporter#95]
I'm keen on using this reporting package for a set of cucumberJs API tests. 
As they don't involve any browsers/devices, is there a way to 'disable' metadata options like browser, OS, device?

**Comment by wswebcreation** [comment]
Currently not, but I add it to my to-do list

**Comment by agliolio** [comment]
great! thank you.
