### ISSUE TITLE
Attaching videos and other files to error section in report

### ISSUE THREAD

**Issue by h-vardhan** [wswebcreation/multiple-cucumber-html-reporter#99]
**Describe your question with as much detail as possible**
I am using multiple cucumber reporter for my Testcafe tests. Whenever an error happens, screenshot is captured by Testcafe and later after the run is completed, cucumber report is generated which shows the screenshot at the step of a failed test. My Testcafe tests also record videos during failure cases. How can I provide a link for video in failed test step in the cucumber report, besides the existing link for the screenshot, so that when I click on video, the video plays?

**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.12.1
 - Node.js version: 12.6.0
 - NPM version: 6.9.0
 - Platform name and version: MacOS Sierra High 10.13.6
 - testcafe: 1.4.1
 - testcafe-reporter-cucumber-json: 2.0.0

**Comment by wswebcreation** [comment]
Hi @h-vardhan 

For cucumber you can always attach data to the JSON report. I was quite surprised that there is even a CucumberJS implementation for TestCafe that uses this module. I would advice you to contact the people who created the module and ask them how to attach data to the reporter.
